### ISSUE TITLE
Restart for version 4.0

### ISSUE THREAD

**Issue by jisle15064468204** [lemmingDev/ESP32-BLE-Gamepad#102]
Download the gamepad instance to the development board and connect the Bluetooth development board to restart!

**Comment by lemmingDev** [comment]
Hi
Please give me the exact code you are trying to run so I can test it
Thanks

**Comment by jisle15064468204** [comment]
I use platformio download have restart occure,howevet used Arduino IDE is ok.

**Comment by lemmingDev** [comment]
I do not use PlatformIO so I am unable to provide support on that

The user @dexterdy that submitted the pull request for most of the 4.0 changes used PlatformIO. Perhaps he can chime in

**Comment by jisle15064468204** [comment]
Ok Thanks very much!

**Comment by lemmingDev** [comment]
So, I got VS Code/PlatformIO installed and Arduino up and running. I compiled a basic gamepad sketch and was able to see it go into a reboot loop a couple of seconds after each time it makes a BT connection

Hopefully dexterdy can take a look

**Comment by lemmingDev** [comment]
I had another crack at using VS Code/Platform IO and I was able to get it working perfectly this time
