### ISSUE TITLE
How to increase default number of Button from 16 to 32 ?

### ISSUE THREAD

**Issue by DenisKozachok** [lemmingDev/ESP32-BLE-Gamepad#105]
In readme said "Library can be configured to use up to 128)"

How to increase the default number of buttons from 16 to 32?

**Comment by lemmingDev** [comment]
https://github.com/lemmingDev/ESP32-BLE-Gamepad/blob/master/examples/TestAll/TestAll.ino

**Comment by DenisKozachok** [comment]
Thanks)

**Comment by lemmingDev** [comment]
NP - Let me know if you're struggling
