### ISSUE TITLE
How to change device name?

### ISSUE THREAD

**Issue by DenisKozachok** [lemmingDev/ESP32-BLE-Gamepad#107]
How to change the device name?

![2022-06-11_18-06-35](https://user-images.githubusercontent.com/29424482/173193719-4d111b10-5da8-4014-8354-29e32dedb91a.png)

**Comment by lemmingDev** [comment]
For now, has to be done in the registry I'm afraid


See here:
https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/77

**Comment by spleen1981** [comment]
Can't fix this in the library I believe.
That name comes from a lookup list based on licensed VID&PID (e.g. [here](https://www.the-sz.com/products/usbid/index.php?v=0x045E&p=&n=)).
So there is no way to put your custom device name in that list unless you buy a license for your own VID/PID.

**Comment by lemmingDev** [comment]
Gotcha - thanks for the explanation

At least there's a registry work around...
