### ISSUE TITLE
PIN MODE: INPUT_PULLUP not working

### ISSUE THREAD

**Issue by saswat711** [lemmingDev/ESP32-BLE-Gamepad#108]
I am trying to make the gamepad using the library but when I am using the input_pull up mode for my buttons. The ble gamepad is not discoverable in my pc or my android phone. The device name is not showing up when I am searching for it to pair with it. But when I am not having the pin mode for my buttons its discoverable by my pc and phone.

**Comment by saswat711** [comment]
Code of Void setup

void setup()
{
        // setup pinmode for JOYSTICKS
     pinMode(xsP,INPUT_PULLUP);
     pinMode(ysP,INPUT_PULLUP);
     pinMode(zP,INPUT_PULLUP);
     pinMode(rzP,INPUT_PULLUP);

         // pinmode for Triggers
     pinMode(ltriP,INPUT_PULLUP);
     pinMode(rtriP,INPUT_PULLUP);

         // pinmode for buttons
     pinMode(aP, INPUT_PULLUP);
     pinMode(bP, INPUT_PULLUP);
     pinMode(xP, INPUT_PULLUP);
     pinMode(yP, INPUT_PULLUP);
     pinMode(lbP, INPUT_PULLUP);
     pinMode(rbP, INPUT_PULLUP);

     pinMode(selP, INPUT_PULLUP);
     pinMode(startP, INPUT_PULLUP);        

    // The default bleGamepad.begin() above enables 16 buttons, all axes, one hat, start and select and no simulation controls
    
        Serial.begin(115200);
        Serial.println("Starting BLE work!");
        bleGamepad.begin();
}

**Comment by lemmingDev** [comment]
Please show your full code so I can see the pins you're trying to use
Also, what board are you using?

**Comment by saswat711** [comment]
I am using esp32 dev kit for it.
I have tried to use it using the Bounce library but still the same issue when I am using INPUT_PULLUP  as pin mode.

#include <Arduino.h>
#include <BleGamepad.h>
#include <Bounce2.h> // For debounceing the switches immediately

#define BOUNCE_WITH_PROMPT_DETECTION // Make button state changes available immediately

BleGamepad bleGamepad;

// Defining Inputs
//joystick
#define xsP 33
#define ysP 32
#define zP 25
#define rzP 26
// trigger
#define ltriP 10
#define rtriP 11
//buttons
#define aP 22
#define bP 23
#define xP 21
#define yP 19
#define lbP 18
#define rbP 2

#define selP 5
#define startP 4

// For bounce objects
#define noButtons 10
byte buttonPins[noButtons] = {ltriP, rtriP, aP, bP, xP, yP, lbP, rbP, selP, startP};
Bounce debouncers[noButtons];

// Joysticks Integer
int XS = 0;
int YS = 0;
int ZS = 0;
int RZS = 0;

// for Trigger
int lTrig = 0 ;
int rTrig = 0;

// for Buttons
int A = 0;
int B = 0;
int X = 0;
int Y = 0;
int sel = 0;
int start = 0;
int Lb = 0;
int Rb = 0;



// function to read joystick values
void readJoy(){
  // For right joystick
  XS = analogRead(xsP);
  YS = analogRead(ysP);
  // for left joystick
  ZS = analogRead(zP);
  RZS = analogRead(rzP);

  Serial.println((String)"X VALUE: "+XS);
  Serial.println((String)"Y VALUE: "+YS);
  Serial.println((String)"Z VALUE: "+ZS);
  Serial.println((String)"RZ VALUE: "+RZS);     
}



// function to read trigger values
//buttonPins index 0-ltriP, 1-rtriP 
void readTrig(){
  // For Triggers
  rTrig = debouncers[0].read();
  lTrig = debouncers[1].read();
  Serial.println((String)"Trigger Values: left Trig- "+lTrig+" Right Trig: "+rTrig);
}



// function to read Buttons values
void readButs(){
  // to read buttons
  //abxy
  //buttonPins index 2-aP, 3-bP,  4-xP, 5-yP
  A = debouncers[2].read();
  B = debouncers[3].read();
  X = debouncers[4].read();
  Y = debouncers[5].read();


  // select,back,reset,start
   //buttonPins index 6-lbP, 7-rbP,  8-selP, 9-startP
  sel = debouncers[6].read();
  start = debouncers[7].read();
  Lb = debouncers[8].read();
  Rb = debouncers[9].read();

// To print serial values
  Serial.println((String)"A, B, X, Y: "+A+" "+B+" "+X+" "+Y);
  Serial.println((String)"select, start, leftBtn, rightBtn: "+sel+" "+start+" "+Lb+" "+Rb);

}



// Updating  Values
void updateVal(){
  // updating joystick values
    Serial.println((String)"Updating Values: ");
    XS = map(XS,0,4095, 32767, -32767);
    YS = map(YS,0,4095, -32767, 32767);  
    ZS = map(ZS,0,4095, 32767, -32767);  
    RZS = map(RZS,0,4095, 32767, -32767);  

    bleGamepad.setLeftThumb(XS,YS);
    bleGamepad.setRightThumb(ZS,RZS);
    Serial.println((String)"Updated joysticks Values: ");     

    // For updating Trigger values

    // For updating buttons values
     //To update values abxy
  if(A){
        bleGamepad.press(BUTTON_1);
  }
  else{
     bleGamepad.release(BUTTON_1);
  }
  if(B){
        bleGamepad.press(BUTTON_2);
  }
  else{
      bleGamepad.release(BUTTON_2);
  }
  if(X){
        bleGamepad.press(BUTTON_3);
  }
  else{
      bleGamepad.release(BUTTON_3);
  }
  if(Y){
        bleGamepad.press(BUTTON_4);
  }
  else{
      bleGamepad.release(BUTTON_4);
  }
  // For functions button
  if(sel){
    bleGamepad.pressSelect();
    bleGamepad.releaseSelect();
  }
  if(start){
     bleGamepad.pressStart();
     bleGamepad.releaseStart();
  }
  if(Lb){
     bleGamepad.press(BUTTON_5);
  }
  else{
      bleGamepad.release(BUTTON_5);
  }
  if(Rb){
     bleGamepad.press(BUTTON_6);
  }
  else{
      bleGamepad.release(BUTTON_6);
  }   
}



void setup()
{
  // for attachign debouncers with the pins
  for(byte i=0; i< noButtons;i++){
    debouncers[i] = Bounce();
    debouncers[i].attach(buttonPins[i], INPUT_PULLUP);
    debouncers[i].interval(5);
 
  }    
    // The default bleGamepad.begin() above enables 16 buttons, all axes, one hat, start and select and no simulation controls
        bleGamepad.begin();
        Serial.begin(115200);
        Serial.println("Starting BLE work!");
}


void loop()
{
// put your main code here, to run repeatedly:
     
   if (bleGamepad.isConnected())
    {
        Serial.println("Ble is connected");

       for(byte i=0; i< noButtons;i++)
         {
           debouncers[i].update();
         }
        // reading joystic values
        readJoy();

        // reading trigger values
        readTrig();

        // reading buttons values
        readButs();
        delay(100); 
       
        // updating values in BleGampad
        updateVal();
    }
   else
    {
        Serial.println("Ble is not connected!"); 
                delay(500);
    }
}

**Comment by lemmingDev** [comment]
https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

So, it seems you are using pins you shouldn't be.

Pins 10 and 11 are connected to the internal SPI Flash and shouldn't be used in your sketch.

Also, I think the analogs should just be INPUT, not INPUT_PULLUP

**Comment by saswat711** [comment]
You are right the issue was with pins 10 and 11 thanks for the fix.
The internal SPI Flash was not making it discoverable in my devices.  I have used the analog pins as INPUT only not INPUT_PULLUP
