### ISSUE TITLE
Missing Libraries

### ISSUE THREAD

**Issue by ddragon1999** [lemmingDev/ESP32-BLE-Gamepad#11]
I am trying to "Verify" this code using Arduino 1.8.12 and I am coming up with a bunch of missing libraries. I was able to find most of them but the latest I am stuck on is "#include <bits/libc-header-start.h>". I cannot find it anywhere. Does anybody know how to get it.

**Comment by T-vK** [comment]
Did you follow all the [installation instructions](https://github.com/lemmingDev/ESP32-BLE-Gamepad#installation)?

**Comment by ddragon1999** [comment]
My bad I totally jumped the gun and just ran Arduino IDE with the code. I will follow the instructions from https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/windows.md
Thanks for the reply
