### ISSUE TITLE
Explications for use please

### ISSUE THREAD

**Issue by peperounez** [lemmingDev/ESP32-BLE-Gamepad#113]
Hello,
I'm having some difficulty understanding how to use this gamepad.
How to declare the pins on the ESP32 to be used for sticks, buttons?
I understand that there is also self-study, can you confirm?
Would it be possible to have a tutorial in video or images with a typical gamepad (2 pads of 4 buttons, 2 joysticks, 2 buttons (start, stop), 4 trigger buttons (2 on the right, 2 on the left)) Example of an xbox one controller.
Thanks for the help and sorry for my English, I'm French.
Have a nice day

**Comment by LeeNX** [comment]
Greetings...

https://youtu.be/dODmsoAu0D4

Enjoy

**Comment by peperounez** [comment]
Hello,
I had seen this video but had not made the connection.
Thanks a lot
