### ISSUE TITLE
Is your gamepad joysticks the same as an Xbox Controller

### ISSUE THREAD

**Issue by lewisjustin749** [lemmingDev/ESP32-BLE-Gamepad#115]
Hi, I am using an adafruit ESP 32 feather and I am emulating an Xbox to use as an input device for a VR headset. 
To do this I need to have the first two buttons working and the right joystick working.
I tried using your library and on gamepad testers I seem to see the joystick immediately stay in the extreme values such as 1,1 or -1,1. 
My analog pin is a 12 - bit ADC and I am wondering how the best way is to program the joystick to spit out similar values a Xbox controller would

**Comment by lemmingDev** [comment]
https://github.com/lemmingDev/ESP32-BLE-Gamepad/releases/tag/v0.5.0

Problem solved in the new version
