### ISSUE TITLE
Right Thumbstick Y Axis

### ISSUE THREAD

**Issue by lewisjustin749** [lemmingDev/ESP32-BLE-Gamepad#116]
Trying to configure the right joystick and I'm noticing that Rz is controlling the left thumbstick's X-axis. What is the proper way to set up a right thumbstick so that it's properly recognized?

**Comment by lemmingDev** [comment]
Hi

I've just checked the library and it's working as intended

In the HID report that is used to set the gamepad up, there is no Left Thumbstick or Right Thumbstick defined

It's just the operating system that usually sees X and X axes as the left thumbstick and Z and rZ axes as the right thumbstick (and rX and rY as the triggers)

My guess is that you're on an OS other than Windows yeah?

**Comment by lemmingDev** [comment]
Let me know if you need me to re-open this
