### ISSUE TITLE
isConnected always false

### ISSUE THREAD

**Issue by przemekszukala** [lemmingDev/ESP32-BLE-Gamepad#129]
With new 5.0 version bleController.isConnected() always gives false, even with gamepad example without any changes, so nothing is being sent to the computer.
I think newest nimBLE version isn't compatible, it works with version before last commits.
https://github.com/h2zero/NimBLE-Arduino/tree/a638a6d1417d487ff51153fde99c045138b2776d

**Comment by lemmingDev** [comment]
https://github.com/lemmingDev/ESP32-BLE-Gamepad/releases/tag/v0.5.1

So, use the new v5.1 of this library, plus the official v1.4.0 version of NimBLE (from library manager)

They keep updating the GitHub master version without providing an official release and it's causing breaking changes, so just use the above versions for now
