### ISSUE TITLE
Library compile error (bleKeyboardInstance)

### ISSUE THREAD

**Issue by itarozzi** [lemmingDev/ESP32-BLE-Gamepad#13]
The new line introduced in the commit 7b6ed11ba874833ae575d102272759ae45993a84 containing bleKeyboardInstance causes error in library compilation (example compilation). 

Commenting out that line I can compile the Gamepad example.

**Comment by T-vK** [comment]
It probably should have been something like `bleGamepadInstance` instead.

**Comment by lemmingDev** [comment]
I'll fix it up when I get to a computer

**Comment by lemmingDev** [comment]
Fixed...
