### ISSUE TITLE
Pressing button set hat and axis to 0

### ISSUE THREAD

**Issue by Peluko** [lemmingDev/ESP32-BLE-Gamepad#14]
Hello. When ```press()``` is called, the axis and hat are reseted to 0, due to this code:

https://github.com/lemmingDev/ESP32-BLE-Gamepad/blob/ce8cf9e98137e93be4efaa5ee9720a284aea2bc5/BleGamepad.cpp#L121

This code is required for something? I think that it's only there to notify the button change, but it also resets values to 0.

I've solved this here:

https://github.com/Peluko/ESP32-BLE-Gamepad/commit/9f42f703fc9b53011f3f2f7aabb345dd0410d12c

by changing the logic for checking and notifying changes (take a look at ```_previousState``` and ```_currentState```).

**Comment by lemmingDev** [comment]
The library has been updated to solve this issue
