### ISSUE TITLE
What does Autoreport "do and not do"

### ISSUE THREAD

**Issue by GamingNJncos** [lemmingDev/ESP32-BLE-Gamepad#140]
This is more a discussion item but for clarity I'm curious as to what " bleGamepadConfig.setAutoReport()" false and true states actually accomplish?  I've dug through documentation, code, and examples but don't see it clearly outlined anywhere.  

Looking over the code, it looks like it's just calling on the backend sendreport at each state read. For context, I'm looking to confirm if this is just an ease of use feature or has a less obvious inherent advantage.  As far as I can locate, there's no actual button "state tracking" used in autoreport.  

 For example in BleGamepad.cpp 
```
void BleGamepad::releaseSpecialButton(uint8_t b)
{
    uint8_t button = specialButtonBitPosition(b);
    uint8_t bit = button % 8;
    uint8_t bitmask = (1 << bit);

    uint64_t result = _specialButtons & ~bitmask;

    if (result != _specialButtons)
    {
        _specialButtons = result;
    }

    if (configuration.getAutoReport())
    {
        sendReport();
    }
}
```

There is an example of state tracking in [Multiple buttons example](https://github.com/lemmingDev/ESP32-BLE-Gamepad/blob/master/examples/MultipleButtons/MultipleButtons.ino)
```
if (currentButtonStates != previousButtonStates)
        {
            for (byte currentIndex = 0; currentIndex < numOfButtons; currentIndex++)
            {
                previousButtonStates[currentIndex] = currentButtonStates[currentIndex];
            }

            bleGamepad.sendReport();
        }
```

This is purely pedantic (sorry) and gets a bit into the weeds for BLE as a protocol but does tie to potential performance issues. BLE requires an ACK for each packet at link layer.  If using either "autoreport" or manually calling "sendpress" results in constantly flooding "not pressed" as a packet, depending on your polling rate (how fast you are checking states) there is potential to significantly impact latency for new presses.  

 You can read a bit more about it [HERE](https://interrupt.memfault.com/blog/ble-throughput-primer)
 "The BLE Link Layer protocol is reliable meaning every packet of data sent from one side must be acknowledged (ACK’d) by the other."
 
I suspect the ultimate answer is "Just manually track the state" but wanted to confirm if I was missing anything centric to using Auto that aids in alleviating this scenario.  For situations where you are trying to avoid "delay()", combined with a high mhz Esp32 clock (240mhz for example) potential to run into this grows exponentially.

**Comment by lemmingDev** [comment]
Hi

Auto report is just for convenience, and it's better to look after the state yourself. It was included on another USB gamepad library I saw somewhere, so I added it

A lot of people using the library have little to no programming experience

This is also my one and only go at creating a library.

Feel free to make pull requests to make it more efficient
