### ISSUE TITLE
Compatibility with ESP32 Boards

### ISSUE THREAD

**Issue by gernoff** [lemmingDev/ESP32-BLE-Gamepad#143]
Will the software work with any of the ESP32 BLE boards?
Compatibility list?

**Comment by LeeNX** [comment]
All the ESP32 devices with bluetooth should work - https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/hw-reference/chip-series-comparison.html

ESP32-S2 does not have bluetooth, therefore will not work.   
  
Personally tested on ESP32 and ESP32-C3 dev boards with success.
