### ISSUE TITLE
Is it possible to set password?

### ISSUE THREAD

**Issue by patrykskrzyniarz** [lemmingDev/ESP32-BLE-Gamepad#146]
Hi, great work.
but I'm curious if it is possible to set a password for the connection so that only authorized devices can connect to esp?

**Comment by LeeNX** [comment]
As ESP32-BLE-Gamepad library uses ESP32 BLE library, you can take a look at how they expose the security options. Something like https://github.com/h2zero/NimBLE-Arduino/blob/1cddddb8b82c35d60c81a3bb6732b074c3e64b63/examples/Refactored_original_examples/BLE_server_multiconnect/BLE_server_multiconnect.ino#L46

Thou the power on and pair with a host device that has requested and completing the pairing process, means that no other host device can connect to the ESP32 until pairing is removed.

I have run into a problem where a host device was paired, not connected and the ESP32 would not re-start the pairing process. Possible that I might have done something odd. Turning off the BlueTooth host device adapter and re-power-cycling the ESP32 device, would only then allow pairing too another host device.   
  
I hope that helps.
