### ISSUE TITLE
Wake from sleep issue

### ISSUE THREAD

**Issue by gernoff** [lemmingDev/ESP32-BLE-Gamepad#150]
Realize this is not a specific issue of the code, realize its probably my lack of knowledge.  Hope its OK to post this here.

Cut and pasted together the following code, everything works fine except sleep mode.

Using:  esp_sleep_enable_ext0_wakeup(GPIO_NUM_37, LOW);

But it is going into sleep every:  #define MINUTES_TO_STANDBY 2
 then  immediately waking with the following:

rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 271414342, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13160
load:0x40080400,len:3036
entry 0x400805e4
Initializing...
Boot number: 596
Wakeup caused by external signal using RTC_CNTL
4.10

It looks like its waking via EXT1_wakeup........

`#include <ESP32Encoder.h>  // https://github.com/madhephaestus/ESP32Encoder
#include <Keypad.h>        // https://github.com/Chris--A/Keypad
#include <BleGamepad.h>    // https://github.com/lemmingDev/ESP32-BLE-Gamepad

#define BATTERY_READ_VOLTAGE_PIN 35

#define BUTTONPIN 37 // Pin button is attached to
#define MINUTES_TO_STANDBY 2
#define numOfButtons 16
#define numOfHatSwitches 0
#define enableX false
#define enableY false
#define enableZ false
#define enableRX false
#define enableRY false
#define enableRZ false
#define enableSlider1 false
#define enableSlider2 false
#define enableRudder false
#define enableThrottle false
#define enableAccelerator false
#define enableBrake false
#define enableSteering false

RTC_DATA_ATTR int bootCount = 0; //stays in memory after standby
volatile int countTimerInterrupt;
int standbyCounter = 0;
float percentCharged = 100;
int read_raw;
float voltage_value;
bool pushedSent = false;

//the init for the timerInterrupt
hw_timer_t * timer = NULL;
portMUX_TYPE timerMux = portMUX_INITIALIZER_UNLOCKED;

// Code with critica section for the sleepmode (standby) timer
void IRAM_ATTR onTime() {
  portENTER_CRITICAL_ISR(&timerMux);
  countTimerInterrupt++;
  portEXIT_CRITICAL_ISR(&timerMux);
}

// Create encoder objects
ESP32Encoder encoder1;
ESP32Encoder encoder2;
//ESP32Encoder encoder3;
//ESP32Encoder encoder4;

// Variables to store the current encoder count
int32_t encoder1Count = 0;
int32_t encoder2Count = 0;
//int32_t encoder3Count = 0;
//int32_t encoder4Count = 0;

BleGamepad bleGamepad("MyF1 Wheel", "lemmingDev", percentCharged);  //Shows how you can customise the device name, manufacturer name and initial battery level

#define ROWS 6
#define COLS 2
uint8_t rowPins[ROWS] = { 27, 15, 19, 4, 5, 32};  //ESP32 pins used for rows      --> adjust to suit --> Pinout on board: R1, R2, R3, R4
uint8_t colPins[COLS] = { 12, 13};                        //ESP32 pins used for columns   --> adjust to suit --> Pinout on board: Q1, Q2, Q3, Q4
uint8_t keymap[ROWS][COLS] = 
{
  { 1, 2},  //Buttons  1,  2,  3,  4      --> Used for calulating the bitmask for sending to the library
  { 3, 4},  //Buttons  5,  6,  7,  8      --> Adjust to suit which buttons you want the library to send
  { 5, 6},  //Buttons  9, 10, 11, 12      -->
  { 7, 8},  //Buttons 13, 14, 15, 16      --> Eg. The value 12 in the array refers to button 12
  { 9, 10},
  { 11, 12}
  //{ 13, 14 },
  //{ 15, 16 },
  //{17, 18}
};

Keypad customKeypad = Keypad(makeKeymap(keymap), rowPins, colPins, ROWS, COLS);

//Potentiometers
//const int pot1Pin = 34;                // Potentiometer is connected to GPIO 34 (Analog ADC1_CH6)
//const int pot2Pin = 35;                // Potentiometer is connected to GPIO 34 (Analog ADC1_CH7)
//const int numberOfPotSamples = 5;     // Number of pot samples to take (to smooth the values)
//const int delayBetweenSamples = 4;    // Delay in milliseconds between pot samples

void oneMinuteProcedure() 
{
  if (countTimerInterrupt > 0) {
      portENTER_CRITICAL(&timerMux);
      countTimerInterrupt--;
      portEXIT_CRITICAL(&timerMux);
      batteryCheck();
      standbyModeCheck();
      BleGamepad bleGamepad("MyF1 Wheel", "lemmingDev", percentCharged);
  }
}

void standbyModeCheck() {
  standbyCounter++;
  if (standbyCounter >= MINUTES_TO_STANDBY) {
     countTimerInterrupt = 0; //is this necessary?
     esp_deep_sleep_start();
  }
}

void batteryCheck() {

    read_raw = analogRead(BATTERY_READ_VOLTAGE_PIN);
    voltage_value = (read_raw * 3.3 * 2) / float(4095) + 0.2;
    if (voltage_value < 2.7) {
      percentCharged = 0.0f;
    }
    else if (voltage_value > 4.0 ) {
      percentCharged = 100.0f;
    }
    else {
      percentCharged = ((voltage_value-2.7f)*100)/1.3f;
    }
    Serial.println(voltage_value);
    bleGamepad.setBatteryLevel(int(percentCharged));
}

void KeypadUpdate() 
{
  customKeypad.getKeys();

  for (int i = 0; i < LIST_MAX; i++)  // Scan the whole key list.      //LIST_MAX is provided by the Keypad library and gives the number of buttons of the Keypad instance
  {
    if (customKeypad.key[i].stateChanged)  //Only find keys that have changed state.
    {
      uint8_t keystate = customKeypad.key[i].kstate;

      if (keystate == PRESSED) { bleGamepad.press(customKeypad.key[i].kchar); }  //Press or release button based on the current state
      if (keystate == RELEASED) { bleGamepad.release(customKeypad.key[i].kchar); }

      bleGamepad.sendReport();  //Send the HID report after values for all button states are updated, and at least one button state had changed
    }
  }
}

void setup() 
 {  
  setCpuFrequencyMhz(80); //20-30% batterylife saver
  Serial.begin(115200);
  delay(1000);
  Serial.println("Initializing...");
  //Increment boot number and print it every reboot
  ++bootCount;
  Serial.println("Boot number: " + String(bootCount));
  print_wakeup_reason();
 
 
  pinMode(BUTTONPIN, INPUT_PULLUP); //button
  //bleGamepad.begin();  //button

 
  
  //pinMode(BATTERY_READ_VOLTAGE_PIN,INPUT);
  
 
  //Configure pin as ext0 wake up source for HIGH logic level to activate esp32 out of sleep (standby)
  
  esp_sleep_enable_ext0_wakeup(GPIO_NUM_37, LOW);
  
  // Configure the Prescaler at 80 the quarter of the ESP32 is cadence at 80Mhz
  //80000000 / 80 = 1000000 tics / seconde;
  timer = timerBegin(0, 80, true);                
  timerAttachInterrupt(timer, &onTime, true);    
  // Set the timer interrupt every minute
  timerAlarmWrite(timer, 60000000, true);           
  timerAlarmEnable(timer);
  
  
  //analogReadResolution(9);

  
  
  // Enable the weak pull up resistors
  ESP32Encoder::useInternalWeakPullResistors = UP;

  // Attach pins to encoders
  encoder1.attachFullQuad(22, 20);
  encoder2.attachFullQuad(7, 8);
  //encoder3.attachHalfQuad(32, 27);
  //encoder4.attachHalfQuad(5, 4);

  // Clear encoder counts
  encoder1.clearCount();
  encoder2.clearCount();
  //encoder3.clearCount();
  //encoder4.clearCount();

  // Initialise encoder counts
  encoder1Count = encoder1.getCount();
  encoder2Count = encoder2.getCount();
  //encoder3Count = encoder3.getCount();
  //encoder4Count = encoder4.getCount();

  // Setup controller with 16 buttons
  BleGamepadConfiguration bleGamepadConfig;
  bleGamepadConfig.setAutoReport(false);
  bleGamepadConfig.setControllerType(CONTROLLER_TYPE_GAMEPAD);  // CONTROLLER_TYPE_JOYSTICK, CONTROLLER_TYPE_GAMEPAD (DEFAULT), CONTROLLER_TYPE_MULTI_AXIS
  bleGamepadConfig.setButtonCount(numOfButtons);
  //bleGamepadConfig.setWhichAxes(enableX, enableY, enableZ, enableRX, enableRY, enableRZ, enableSlider1, enableSlider2);      // Can also be done per-axis individually. All are true by default
  //bleGamepadConfig.setWhichSimulationControls(enableRudder, enableThrottle, enableAccelerator, enableBrake, enableSteering); // Can also be done per-control individually. All are false by default
  //bleGamepadConfig.setHatSwitchCount(numOfHatSwitches);                                                                      // 1 by default
  // Some non-Windows operating systems and web based gamepad testers don't like min axis set below 0, so 0 is set by default
  //bleGamepadConfig.setAxesMin(0x8001); // -32767 --> int16_t - 16 bit signed integer - Can be in decimal or hexadecimal
  //bleGamepadConfig.setAxesMax(0x7FFF); // 32767 --> int16_t - 16 bit signed integer - Can be in decimal or hexadecimal
  batteryCheck();
  bleGamepad.begin(&bleGamepadConfig);
  // changing bleGamepadConfig after the begin function has no effect, unless you call the begin function again
}

void EncodersUpdate() 
{
  int32_t tempEncoderCount1 = encoder1.getCount();
  int32_t tempEncoderCount2 = encoder2.getCount();
  //int32_t tempEncoderCount3 = encoder3.getCount();
  //int32_t tempEncoderCount4 = encoder4.getCount();

  bool sendReport = false;

  if (tempEncoderCount1 != encoder1Count) 
  {
    sendReport = true;

    if (tempEncoderCount1 > encoder1Count) {
      bleGamepad.press(BUTTON_16);
    } else {
      bleGamepad.press(BUTTON_15);
    }
  }

  if (tempEncoderCount2 != encoder2Count) 
  {
    sendReport = true;

    if (tempEncoderCount2 > encoder2Count) {
      bleGamepad.press(BUTTON_14);
    } else {
      bleGamepad.press(BUTTON_13);
    }
  }

  if (sendReport) 
  {
    bleGamepad.sendReport();
    delay(400);

    bleGamepad.release(BUTTON_13);
    bleGamepad.release(BUTTON_14);
    bleGamepad.release(BUTTON_15);
    bleGamepad.release(BUTTON_16);
    //bleGamepad.release(BUTTON_23);
    //bleGamepad.release(BUTTON_24);
    //bleGamepad.release(BUTTON_25);
    ////bleGamepad.release(BUTTON_26);
    bleGamepad.sendReport();
    delay(300);
    encoder1Count = encoder1.getCount();
    encoder2Count = encoder2.getCount();
    //encoder3Count = encoder3.getCount();
    //encoder4Count = encoder4.getCount();
  }
}

void print_wakeup_reason(){
  esp_sleep_wakeup_cause_t wakeup_reason;
  wakeup_reason = esp_sleep_get_wakeup_cause();
  switch(wakeup_reason)
  {
    case 1  : Serial.println("Wakeup caused by external signal using RTC_IO"); break;
    case 2  : Serial.println("Wakeup caused by external signal using RTC_CNTL"); break;
    case 3  : Serial.println("Wakeup caused by timer"); break;
    case 4  : Serial.println("Wakeup caused by touchpad"); break;
    case 5  : Serial.println("Wakeup caused by ULP program"); break;
    default : Serial.println("Wakeup was not caused by deep sleep"); break;
  }
}
void loop() {
 
  if (bleGamepad.isConnected()) 
  {
    KeypadUpdate();
    EncodersUpdate();
    //oneMinuteProcedure(); 
    //PotentiometersUpdate();
    delay(10);
  }
  oneMinuteProcedure(); 
}`

**Comment by lemmingDev** [comment]
Not sure sorry. Have never tried deep sleep
Doesn't look like anyone else wants to jump in so will close
