### ISSUE TITLE
Is it still possible to support ios devices?

### ISSUE THREAD

**Issue by huzhiyuan1994** [lemmingDev/ESP32-BLE-Gamepad#151]
I noticed that the IOS 16 has supported the connection of Nintendo JoyCon/Pro controller. And there some project has used the ESP32 to simulate a Nintendo controller. So, does this mean that it can be used to achieve compatibility with ios devices by this way (although this limits the custom keys).
see:
https://github.com/elmagnificogi/NS_joycon_auto_script_esp32
https://github.com/EasyConNS
https://github.com/EasyConNS/EasyMCU_ESP32

**Comment by lemmingDev** [comment]
I won't be having a crack at it, but if anyone else wants to; have at it...

**Comment by lemmingDev** [comment]
Not within scope of the project - closing
