### ISSUE TITLE
Not able to access right thumb stick and left DPAD.

### ISSUE THREAD

**Issue by Rajan732** [lemmingDev/ESP32-BLE-Gamepad#153]
I want to make a controller like ps4. I was successful in giving the left thumb stick and other button inputs but I cannot access the right thumb stick and left DPAD. I have used all the functions and tried various configurations of code but still, I'm facing the same issue. When I give commands to use the right thumb stick (rX and rY) then also the left thumb stick moves. 

I would really appreciate it if anyone can help me with this.

**Comment by LeeNX** [comment]
Greetings...

Three things come to mind, misconfiguration in (could you share a link to
your code?)

Platform differences and testing tools? Which platform (OS) and what
testing tools are you using?

Have you tried the test all buttons sketch -
https://github.com/lemmingDev/ESP32-BLE-Gamepad/tree/master/examples/TestAll

Or complete project -
https://github.com/palsayantan/BLE-Game-Controller/blob/main/ESP32_BLE_Controller/ESP32_BLE_Controller.ino

My TestAll buttons sketch runs fine on a Raspberry Pi and OSX using an sdl
test gamepad.

Might be worth suggesting process for testing, including some tools. Let me
see what I can do tomorrow.

Thanks
LeeT

**Comment by Rajan732** [comment]
>

**Comment by Rajan732** [comment]
I'm using the example codes of IndividualAxis.ino and TestAll.ino for testing with my ESP32 DEVKIT V1.
I even created my own sketch and tested the functions separately.
For now, I was planning to first see if all the gamepad functions are working. After this, I will add all the necessary buttons and joysticks.

**Comment by Rajan732** [comment]
I saw some closed forums and noticed that there was an issue of not being able to access the triggers and in the comments, it was suggested to use BLE-Gamepad 0.5 and the latest version of NimBLE (1.4.1). I tried this also but in this case although my ESP32 is able to connect to my android phone as a Gamepad but is not giving any input signals.

**Comment by LeeNX** [comment]
After totally breaking my testing environment, I re-downloaded BLE-Gamepad v0.5.3 and NimBLE v1.4.1. I used TestAll and used the above Android App for testing and I think it looks like all buttons doing stuff.
![photo_2022-12-23_12-05-19](https://user-images.githubusercontent.com/792948/209316790-b4448d35-89ad-4e2e-ab31-1173b642f526.jpg)

**Comment by LeeNX** [comment]
Sorry, scrolls a little fast for TestAll, need to slow the button testing down and see if I can better select each test set. I will take a poke at this further, but I don't think there is a problem with the library.

**Comment by Rajan732** [comment]
In the image you sent, the leftTrigger and rightTrigger are working. But in my case, only left axis leftX and leftY are showing.

![Screenshot_2022-12-23-16-06-12-31_f627210d6c3081a761f48e951bf70d0a](https://user-images.githubusercontent.com/78225677/209322002-8cac244f-d706-4d9e-ad89-c6147994f6d4.jpg)

**Comment by Rajan732** [comment]
I changed my board to an ESP32-S and the code is working fine now. Thank you for your help and support @LeeNX

**Comment by LeeNX** [comment]
You're welcome, hope we can figure out why it's not working and others don't run into the same problem.  
  
Interesting, what did you have it set at? I am using a NodeCMU-S2.

**Comment by Rajan732** [comment]
I didn't quite understand your question but I'm using an ESP32-S2-Saola-1

**Comment by LeeNX** [comment]
You saying you changed your physical Esp32 board, not just the ArduinoIDE
definition?

What board were you using?

**Comment by Rajan732** [comment]
I didn't change any Arduino IDE settings. I kept the board at "ESP32 Dev Module" for both the boards.

Previously I used:
https://www.electronicscomp.com/esp32-development-board-with-wifi-bluetooth-india?gclid=EAIaIQobChMIm5GpsM2P_AIVhwsrCh3_Hg-mEAQYASABEgIKpfD_BwE

Then I changed to:
https://robu.in/product/ai-thinker-nodemcu-32s-esp32-development-board-ipex-version/?pid=1304499
