### ISSUE TITLE
0.5.3: Release has wrong version in library.properties 

### ISSUE THREAD

**Issue by rickard-von-essen** [lemmingDev/ESP32-BLE-Gamepad#156]
PlatformIO can't find `0.5.3` since it has version `0.5.2` in the `library.properties` file.

See
https://github.com/lemmingDev/ESP32-BLE-Gamepad/blob/v0.5.3/library.properties#L2

**Comment by hworld** [comment]
Was wondering if there could be a commit to get this through? Would love to update through platformio.

**Comment by lemmingDev** [comment]
Fixed with 0.5.4
