### ISSUE TITLE
button map for different OS.

### ISSUE THREAD

**Issue by Kashyapkoshti** [lemmingDev/ESP32-BLE-Gamepad#158]
can you provide data for button map difference between android and windows ?
I am having difficulties as, for right joystick the axis for windows are AXIS_2 & AXIS_5 but for android these are AXIS_2 & AXIS_3.

**Comment by Kashyapkoshti** [comment]
is there any easy way for selecting button mapping based on the which OS the device is connected?

**Comment by LeeNX** [comment]
I don't think I have seen a BLE exposed idea of the connected server host OS. I could be wrong, if so, please let us know.  
  
I think I have seen a snippet (which I can't find at the moment) that could report ```server``` name and BLE MAC address.  
  
There are a few ways that I think you might be able to set button mappings from the ```BLE-Gamepad``` device/client, like check a button on start up/connect and switch to required mappings. Another way if you have spare GPIO, use a switch to select the mappings. Could also check the BLE server name/mac address and hard coded mapping for sub strings.  
  
Take care not to change the services/characteristic between mappings/changes, as most servers cache the setup to save on battery and reconnection time. Seen funny bugs when they change and the client device is not deleted and re-paired. 

Could also use something like SDL GameControllerMapping https://wiki.libsdl.org/SDL3/SDL_GameControllerMapping, if your target application is SDL based.

Possible a 3rd party tool that does something similar on Android.
