### ISSUE TITLE
win10 cannot find the esp32 ble gamepad

### ISSUE THREAD

**Issue by jinshsa** [lemmingDev/ESP32-BLE-Gamepad#159]
i upload the code to my esp32, my andriod phone can find the "esp32 ble gamepad" and connect to it, but my PC with a bluetooth adapter cann't find it , while my PC can find my phone and send file with my phone.

**Comment by jinshsa** [comment]
> Would need to confirm if the BlueTooth adapter is BlueTooth Low Energy(BLE) supported. Not sure if you can confirm this in Windows. Search in the Windows Device Manager for `Microsoft Bluetooth LE Enumerator`. Should be installed and enabled.

Thanks, I should to try this way

**Comment by lemmingDev** [comment]
![image](https://user-images.githubusercontent.com/15526971/212800748-0e69c424-f4a3-4de4-a952-b9d7711d6a9e.png)

In device manager you should see this one

**Comment by lemmingDev** [comment]
How did you go?

**Comment by VoicesJr** [comment]
I'm having the same issue. But the Bluetooth LE Enumerator driver is installed and enabled.

**Comment by lemmingDev** [comment]
What version of the library are you using?
What code are you trying to run?

**Comment by VoicesJr** [comment]
Hi 
I have 0.5.2 installed of the ESP-BLE-Gamepad. 
The Microsoft Bluetooth LE Enumerator has the Driver version 10.0.19041.488 if thats of any use. I've been trying the example PotAsAxis. It on macOS and I also got the serial print to start working when I connected the ESP32 to an Iphone via BT. 

Gratefull for any help!!

**Comment by VoicesJr** [comment]
I have alsoe tried 0.5.0.

**Comment by LeeNX** [comment]
Do any of the other ESP32 BLE examples work, like the ```BLE_notify```, I think you should be able to see this with ```Bluetooth LE Explorer``` on Windows and/or ```BLE Scanner (Connect & Notify)``` on Android.

**Comment by lemmingDev** [comment]
No response from author - closed
