### ISSUE TITLE
MPU9250

### ISSUE THREAD

**Issue by chazp246** [lemmingDev/ESP32-BLE-Gamepad#16]
Is this library compatibble with mpu9250? I want to do VR controller that will use mpu9250 with some buttons and joystick. Output will be proccesed by Driver4Vr that will map it to vive controller.

Looks promising

**Comment by lemmingDev** [comment]
Hi

There seems to be available libraries for getting the mpu9250 to work on an ESP32 in Arduino, so yes, it will work.
Any sensor compatible with ESP32/Arduino will work.

You'll have to manage getting the values yourself, and mapping them to the values compatible with the library...
