### ISSUE TITLE
Disconnecting from Windows 10

### ISSUE THREAD

**Issue by Narsku** [lemmingDev/ESP32-BLE-Gamepad#166]
Hi, im having problems trying to use the example code in windows 10, the gamepad works fine, but after 15 seconds aprox the gamepad disconnects, i tried with Android and its seems to work just like expected, the problem its only for windows

**Comment by lemmingDev** [comment]
Try this version

https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/111#issuecomment-1254260699
