### ISSUE TITLE
Not able to pair with windows 11 or with Android either

### ISSUE THREAD

**Issue by vrushant2001** [lemmingDev/ESP32-BLE-Gamepad#169]
I am using esp32 wroom board . I downloaded all libraries and iam using multiple buttons example but iam not ble to pair with my pc . It shows "try contacting to device again" but never connects . 
Same with Android (Android 11) phone it doesn't pair

**Comment by level451** [comment]
Any update?

**Comment by vrushant2001** [comment]
2 days ago i bought new esp32 board and it works perfectly with all your example and libraries. I guess it might be hardware problem in previous esp32  though i am still able to use classic Bluetooth and wifi perfectly in that esp32 (faulty one ) just fine .

Thanks for this libraries it is great help for students like me
