### ISSUE TITLE
Error in special buttons example.

### ISSUE THREAD

**Issue by Darkflib** [lemmingDev/ESP32-BLE-Gamepad#180]
On line 66   bleGamepad.releaseSelect(); 

I believe this is a copy/paste error from the first block.

**Comment by LeeNX** [comment]
I think this was fixed by https://github.com/lemmingDev/ESP32-BLE-Gamepad/commit/fff571a54bf13b3503f43b9e59a96ef5fceec44b  
  
If not, can you add more info.

**Comment by Darkflib** [comment]
Confirmed as fixed.
