### ISSUE TITLE
In Windows11 cant scan the device ,But I fixed？

### ISSUE THREAD

**Issue by Cengls** [lemmingDev/ESP32-BLE-Gamepad#183]
Windows11
Esp32c3
Vscode PLA

IN **"BleGamepad.cpp"**
taskserver()
line:1400

Del  **"NimBLEDevice::setSecurityAuth(BLE_SM_PAIR_AUTHREQ_BOND);"**

Then code worked
I learned about BLE ，It seems  like Windows11 Problem？

And another BUG ：
Bluetooth will keep linking after restarting

**Comment by lemmingDev** [comment]
https://github.com/h2zero/NimBLE-Arduino/issues/464#issuecomment-1304653972

I might also follow this advice if it seems to work as well for original ESP32 devices

Will test
