### ISSUE TITLE
REALLY BIG PROBLEM EXAMPLE 

### ISSUE THREAD

**Issue by JuanJoseAriasJaramillo** [lemmingDev/ESP32-BLE-Gamepad#188]
This is your example code called PotAsAxisBLE.ino
yesterday it was working perfectly, but today i open the script to try and learn how to do a code por sim racing pedals, but i got this from arduino ERROR 

/*
 * Reads a potentiometer on pin 34 and maps the reading to the X axis
 *
 * Potentiometers can be noisy, so the sketch can take multiple samples to average out the readings
 */

#include <Arduino.h>
#include <BleGamepad.h>

BleGamepad bleGamepad;

const int potPin = 34;                // Potentiometer is connected to GPIO 34 (Analog ADC1_CH6)
const int numberOfPotSamples = 5;     // Number of pot samples to take (to smooth the values)
const int delayBetweenSamples = 4;    // Delay in milliseconds between pot samples
const int delayBetweenHIDReports = 5; // Additional delay in milliseconds between HID reports

void setup()
{
    Serial.begin(115200);
    Serial.println("Starting BLE work!");
    bleGamepad.begin();
}

void loop()
{
    if (bleGamepad.isConnected())
    {
        int potValues[numberOfPotSamples]; // Array to store pot readings
        int potValue = 0;                  // Variable to store calculated pot reading average

        // Populate readings
        for (int i = 0; i < numberOfPotSamples; i++)
        {
            potValues[i] = analogRead(potPin);
            potValue += potValues[i];
            delay(delayBetweenSamples);
        }

        // Calculate the average
        potValue = potValue / numberOfPotSamples;

        // Map analog reading from 0 ~ 4095 to 32737 ~ 0 for use as an axis reading
        int adjustedValue = map(potValue, 0, 4095, 32737, 0);

        // Update X axis and auto-send report
        bleGamepad.setX(adjustedValue);
        delay(delayBetweenHIDReports);

        // The code below (apart from the 2 closing braces) is for pot value degugging, and can be removed
        // Print readings to serial port
        Serial.print("Sent: ");
        Serial.print(adjustedValue);
        Serial.print("\tRaw Avg: ");
        Serial.print(potValue);
        Serial.print("\tRaw: {");

        // Iterate through raw pot values, printing them to the serial port
        for (int i = 0; i < numberOfPotSamples; i++)
        {
            Serial.print(potValues[i]);

            // Format the values into a comma seperated list
            if (i == numberOfPotSamples - 1)
            {
                Serial.println("}");
            }
            else
            {
                Serial.print(", ");
            }
        }
    }
}
-----------------------------
ERROR
C:\Development\Arduino proyectos\PotAsAxisBLE\Example_code.ino:4:12: error: redefinition of 'BleGamepad bleGamepad'
 BleGamepad bleGamepad;
            ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:11:12: note: 'BleGamepad bleGamepad' previously declared here
 BleGamepad bleGamepad;
            ^
C:\Development\Arduino proyectos\PotAsAxisBLE\Example_code.ino: In function 'void setup()':
C:\Development\Arduino proyectos\PotAsAxisBLE\Example_code.ino:6:6: error: redefinition of 'void setup()'
 void setup()
      ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:18:6: note: 'void setup()' previously defined here
 void setup()
      ^
C:\Development\Arduino proyectos\PotAsAxisBLE\Example_code.ino: In function 'void loop()':
C:\Development\Arduino proyectos\PotAsAxisBLE\Example_code.ino:14:6: error: redefinition of 'void loop()'
 void loop()
      ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:25:6: note: 'void loop()' previously defined here
 void loop()
      ^
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino: At global scope:
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino:12:11: error: redefinition of 'const int potPin'
 const int potPin = 34;                // Potentiometer is connected to GPIO 34 (Analog ADC1_CH6)
           ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:13:11: note: 'const int potPin' previously defined here
 const int potPin = 34;                // Potentiometer is connected to GPIO 34 (Analog ADC1_CH6)
           ^
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino:13:11: error: redefinition of 'const int numberOfPotSamples'
 const int numberOfPotSamples = 5;     // Number of pot samples to take (to smooth the values)
           ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:14:11: note: 'const int numberOfPotSamples' previously defined here
 const int numberOfPotSamples = 5;     // Number of pot samples to take (to smooth the values)
           ^
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino:14:11: error: redefinition of 'const int delayBetweenSamples'
 const int delayBetweenSamples = 4;    // Delay in milliseconds between pot samples
           ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:15:11: note: 'const int delayBetweenSamples' previously defined here
 const int delayBetweenSamples = 4;    // Delay in milliseconds between pot samples
           ^
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino:15:11: error: redefinition of 'const int delayBetweenHIDReports'
 const int delayBetweenHIDReports = 5; // Additional delay in milliseconds between HID reports
           ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:16:11: note: 'const int delayBetweenHIDReports' previously defined here
 const int delayBetweenHIDReports = 5; // Additional delay in milliseconds between HID reports
           ^
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino: In function 'void setup()':
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino:17:6: error: redefinition of 'void setup()'
 void setup()
      ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:18:6: note: 'void setup()' previously defined here
 void setup()
      ^
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino: In function 'void loop()':
C:\Development\Arduino proyectos\PotAsAxisBLE\assd.ino:24:6: error: redefinition of 'void loop()'
 void loop()
      ^
C:\Development\Arduino proyectos\PotAsAxisBLE\PotAsAxisBLE.ino:25:6: note: 'void loop()' previously defined here
 void loop()
      ^

exit status 1

Compilation error: redefinition of 'BleGamepad bleGamepad'

**Comment by LeeNX** [comment]
Guessing in a big way, but that looks like you might have three ```ino``` files in the same folder:
```Example_code.ino```
 ```PotAsAxisBLE.ino```
```assd.ino```

Arduino IDE normally only has one ```ino``` file per project/folder.
