### ISSUE TITLE
[Question] Clear flash settings API (Discoverability after disconnecting with MacOSX)

### ISSUE THREAD

**Issue by victorzzt** [lemmingDev/ESP32-BLE-Gamepad#193]
Only happens on MacOSX
Use the library, pair with a Mac, then disconnect the power, reconnect the power, the Mac will show the device as not connected.
Click forget device on Mac and then the Device will never be discoverable by any computers even flashing other BLEgamepad sketches (Can change mac address, vid, pid, name, vender etc all will not work).

Flashing using "erase all flash before uploading sketches" makes the device discoverable again.
So there must be a settings that's saved in flash that is persistent that's remembering the settings. (It's weird that windows can always reconnect after power cycle of the device, and make the device discoverable again after removing, there must be something that MacOSX does that get the statemachine "stuck" in a state).

So I guess the quick solution is to make a longpress button that can reset the paring settings in flash and do a soft reboot.

Is there an API that can quickly do that? Or is there any range of flash that I need to erase and do a soft reset to achieve the same thing?
Thanks a lot.

**Comment by lemmingDev** [comment]
Hi

Just did extensive testing on a desktop Mac with latest Mac OS Sonoma

It worked perfectly to reconnect back to the Mac in all scenarios, and then when the Mac was turned off, allowed me to pair the exact same device without issue to a Windows PC

I was unable to reproduce any weirdness described above

I can only suggest that you update to the latest Mac OS, or test with another ESP32
