### ISSUE TITLE
pointy joystick app not working on windows 11

### ISSUE THREAD

**Issue by tdguchi** [lemmingDev/ESP32-BLE-Gamepad#197]
Hi, im trying your library, but i cant test it, the test app you suggest is very old, (it uses net 2.0 and 3.0) after installing them, app simply doesnt start.

Is there any other alternative? 

thanks

**Comment by lemmingDev** [comment]
Hi

It's not a 'Windows 11' issue

It's a 'I don't have Direct X 9 installed' issue

https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by tdguchi** [comment]
Wow Dx9... xDD thanks, i will give it a try

**Comment by lemmingDev** [comment]
No problem

Good luck with your custom controller
