### ISSUE TITLE
Compatible with Android

### ISSUE THREAD

**Issue by CiriousJoker** [lemmingDev/ESP32-BLE-Gamepad#2]
I just tested it and it seems like the example is working correctly. Haven't tried ALL the possibilities but axis and buttons seem to work since my bluetooth connection menu is going crazy right now

**Comment by lemmingDev** [comment]
Thanks for letting me know

Did you end up using it for anything interesting?

**Comment by CiriousJoker** [comment]
Not so far, no. Some other more important projects got in the way

**Comment by sh7dm** [comment]
For me it works fine on Android, Linux (Manjaro with 5.7 kernel) supports this as well.

**Comment by lemmingDev** [comment]
Glad it's of some use

Thanks for testing
