### ISSUE TITLE
Absolute Positioning on Android/iOS?

### ISSUE THREAD

**Issue by Nesh108** [lemmingDev/ESP32-BLE-Gamepad#20]
Hello @lemmingDev,

I read here (https://github.com/nkolban/esp32-snippets/issues/230) that you managed to get the absolute positioning working. Does that mean it works on Android and/or iOS too?

I am curious as I am trying to do something like the lightgun you linked but I cannot seem able to get it right. Could you give some guidance? 😄

**Comment by lemmingDev** [comment]
I'm not sure absolute positioning works on iOS or Android

**Comment by lemmingDev** [comment]
There is some discussion here

https://github.com/T-vK/ESP32-BLE-Mouse/issues/19
