### ISSUE TITLE
Thumbstick ideal position drift 

### ISSUE THREAD

**Issue by vigneshappanraj** [lemmingDev/ESP32-BLE-Gamepad#203]
Hi, first thanks for creating this library super useful, 

Beginner here, was trying to connect make a bluetooth duel thumbstick using ESP32 along with BLE-Gamepad library,

I mapped the analogy values from the thumbstick using the below code, and when connected to an android app, both the sticks has drift, I am not sure, what is the issue, searched on the internet coudnt find anything.

Please help me in resolving this issue.

P.S I am connecting my thumbstick in 3.3v,
ESP32 WROOM-32

    // LEFT ANALOG PIN
    int value1 = map(analogRead(LH), 0, 4095,  0, 65475);
    int value2 = map(analogRead(LV), 0, 4095, 65475, 0);
    bleGamepad.setLeftThumb(value1, value2);
    
    // RIGHT ANALOG PIN
    int value3 = map(analogRead(RH), 0, 4095, 0, 65475);
    int value4 = map(analogRead(RV), 0, 4095, 65475, 0);
    bleGamepad.setRightThumb(value3, value4);

Thank you much appreaciated.

**Comment by lemmingDev** [comment]
Perhaps you need a dead zone

Read right through this thread for some ideas
https://forum.arduino.cc/t/adding-a-dead-zone-to-a-analog-imput-on-arduino-leonardo/662508

**Comment by lemmingDev** [comment]
No response in a couple of months

Will close for now. Please respond if you still need help
