### ISSUE TITLE
Unable to use Rudder

### ISSUE THREAD

**Issue by iurycarlos** [lemmingDev/ESP32-BLE-Gamepad#204]
Hello guys!

I took a look at the samples and used the Flight Simulator Test as starting point.
Removed all debug / log stuff and set pins and available buttons / axis.
However,  for some reason, i can't make RUDDER to appear at Windows Joystick Properties.

I only can see Throttle and Brake. Is there anything else we should set?

**Comment by LeeNX** [comment]
I don't have Windows, so can't confirm the RUDDER not showing up. Have you tried to see what https://hardwaretester.com/gamepad on Chrome displays?
<img width="1613" alt="Screenshot 2024-02-13 at 18 29 38" src="https://github.com/lemmingDev/ESP32-BLE-Gamepad/assets/792948/9541e420-dabe-488c-87bd-f9fb275f4409">

In the screenshot you can see Arduino serial console and the gamepad testing for the right side joystick, as an example.  
  
Labels and buttons are not standard and differ between platforms, thou I think @lemmingDev tests on Windows.

**Comment by lemmingDev** [comment]
Windows doesn't show all available axes / buttons

If you enable throttle and rudder (no brake), you will see that the rudder displays fine

![image](https://github.com/lemmingDev/ESP32-BLE-Gamepad/assets/15526971/eb3ae344-dacf-4768-957a-139528741f39)

With throttle, rudder and brake enabled, all show in the gamepad tester above, and games would be able to access the axis
