### ISSUE TITLE
GamePad not visible

### ISSUE THREAD

**Issue by dimityrivanov** [lemmingDev/ESP32-BLE-Gamepad#205]
When I compile the gamepad sketch on the ESP32 the device is not visible on any platform with bluetooth, any idea what might be the reason ?

@lemmingDev I managed to connect it once to my android phone after that I forget the device on the phone and no matter how many times I try to flash it the gamepad don't appear again am I doing something wrong ?

Device I am using is ESP32-C3

**Comment by dimityrivanov** [comment]
Ok I understood what the problem is its here xTaskCreate(this->taskServer, "server", 20000, (void *)this, 5, NULL) this (void *) this is not passed appropriately and if you execute the code without the xTask all works fine but it hangs here if you use the task  BleGamepad *BleGamepadInstance = (BleGamepad *)pvParameter;

@lemmingDev Any idea how to rewrite this to work ?

**Comment by lemmingDev** [comment]
Hi

This library supports the standard ESP32 only, not the S3 or C3
If you work out how to get it working on other platforms such as the C3, feel free to put a pull request in

**Comment by ebur644** [comment]
Hi,

I was having the same problem with the C3 platform, I changed the priority to be 1 instead of 5 and it worked. 

xTaskCreate(this->taskServer, "server", 20000, (void *)this,  1, NULL);

**Comment by lemmingDev** [comment]
Thanks for the update - will get around to testing whether setting it to 1 works for regular ESP32, and if it does, will set it as the default.

**Comment by lemmingDev** [comment]
It works, so I'll make it the default

Thanks!
