### ISSUE TITLE
BLE icon

### ISSUE THREAD

**Issue by nogueira** [lemmingDev/ESP32-BLE-Gamepad#21]
Is there any way to change the icon that appears on the cell phone?

**Comment by T-vK** [comment]
I doubt it. Maybe if you root/jailbreak your phone you can use some third party app to do it.

**Comment by lemmingDev** [comment]
I guess the icon is defined by the way the device presents itself to the operating system

This USB HID descriptor is set to present itself as a gamepad, so the OS detects that and displays it's corresponding icon
