### ISSUE TITLE
Vibration motor support

### ISSUE THREAD

**Issue by mmmrrjs** [lemmingDev/ESP32-BLE-Gamepad#226]
Would you add vibration motor support to ESP32-BLE-Gamepad?

**Comment by LeeNX** [comment]
@mmmrrjs we already have an issue open to provide Force Feedback/Rumble support - https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/99. 
  
There still is not standard interface, thou I am looking into what and how Android/Chrome support over BLE/HID but I have not found useful information.  
  
Do you have a gamepad or hardware device to test on?
