### ISSUE TITLE
Merging ESP32-BLE-keyboard with  ESP32-BLE-Gamepad

### ISSUE THREAD

**Issue by semihsaydam** [lemmingDev/ESP32-BLE-Gamepad#24]
Dear Sir,
I really appreciate the work you have done. In my project I need to use both keyboard and gamepad features. For example I want to play game using gamepad but i also need to write some string too. I've tried adding both libraries in the same Arduino code but for some reason they are not working together. Do you know how can I achieve this? Thanks in advance.

**Comment by lemmingDev** [comment]
It can be done by integrating them into the same library

Here is an example

https://github.com/blackketter/ESP32-BLE-Combo
