### ISSUE TITLE
Setting axis only works for X, Y, RX, RY (Axis 0, 1, 3, 4)

### ISSUE THREAD

**Issue by JasonARong** [lemmingDev/ESP32-BLE-Gamepad#242]
I had some trouble setting the axes other than X, Y, RX, RY (Axis 0, 1, 3, 4) . For some reasons, I cannot get any readings from the game pad tester, when I am setting those other axes. Please help, thank you!

```
    int xValue = map(analogRead(joystickXPin), 0, JOYSTICK_X_MAX, 32767, 0);
    int yValue = map(analogRead(joystickYPin), 0, JOYSTICK_Y_MAX, 32767, 0);
    bleGamepad.setLeftThumb(xValue, yValue); // Works
    bleGamepad.setX(xValue); // Works
    bleGamepad.setY(yValue); // Works
    bleGamepad.setZ(xValue); // Does not Work
    bleGamepad.setRightThumb(xValue, yValue); // Works
    bleGamepad.setRX(xValue); // Works
    bleGamepad.setRY(yValue); // Works
    bleGamepad.setRZ(xValue); // Does not Work
    bleGamepad.setSlider(xValue); // This and all other sliders do not Work
```
When using `bleGamepad.setLeftThumb(xValue, yValue); `
<img width="945" alt="Screen Shot 2024-12-07 at 1 36 05 PM" src="https://github.com/user-attachments/assets/b0152b9e-ad3e-4e0d-9097-6c3d1b1eebd8">

when using 
```
    bleGamepad.setY(yValue); 
    bleGamepad.setZ(xValue); 
```
<img width="955" alt="Screen Shot 2024-12-07 at 1 37 53 PM" src="https://github.com/user-attachments/assets/5b5572fe-d528-4188-b4bf-fc6f3d4ecad6">

**Comment by LeeNX** [comment]
Have you tested the include example IndividualAxes.ino or even TestAll.ino? Remember to unpair / delete / remove bluetooth device from your host OS.

**Comment by Sab1e-GitHub** [comment]
I used the following code for testing:
```
#include <Arduino.h>
#include <BleGamepad.h>

BleGamepad bleGamepad;

void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE work!");
  bleGamepad.begin();
}

void loop() {
  if (bleGamepad.isConnected()) {
    for (int i = 0; i < 32767; i += 10) {
      int xValue = i;
      int yValue = i;
      bleGamepad.setLeftThumb(xValue, yValue);   // Works
      bleGamepad.setX(xValue);                   // Works
      bleGamepad.setY(yValue);                   // Works
      bleGamepad.setZ(xValue);                   // Does not Work
      bleGamepad.setRightThumb(xValue, yValue);  // Works
      bleGamepad.setRX(xValue);                  // Works
      bleGamepad.setRY(yValue);                  // Works
      bleGamepad.setRZ(xValue);                  // Does not Work
      bleGamepad.setSlider(xValue);              // This and all other sliders do not Work
      delay(1);
    }
  }
}
```

I didn’t find any issues. Please take a look at the GIF below:
![GIF 12-8-2024 2-58-02 AM](https://github.com/user-attachments/assets/9639f31b-91e4-49bf-b888-1c8ba443f4b3)
![GIF 12-8-2024 3-00-53 AM](https://github.com/user-attachments/assets/0933cff9-c3a1-46eb-8de4-ec742b12d7b2)

Could you provide more information?
(By the way, if you are using a custom configuration and have modified the number of buttons or axes, you must remove the device and re-pair it.)

**Comment by JasonARong** [comment]
Thank you for your reply! Your testing code is also working for me. So it must have been me messing something up in my code.

**Comment by Sab1e-GitHub** [comment]
You're welcome!  
Regarding custom configurations, you can find examples [here](https://github.com/lemmingDev/ESP32-BLE-Gamepad/blob/master/examples/CharacteristicsConfiguration/CharacteristicsConfiguration.ino).
