### ISSUE TITLE
Change name in windows gamecontroller settings

### ISSUE THREAD

**Issue by Noplautikus** [lemmingDev/ESP32-BLE-Gamepad#25]
Hello, my esp32 is displayed as "6-Achsen Mehrwegschalter", is it possible to change the displayname. 
![image](https://user-images.githubusercontent.com/46763706/99153222-776da380-26a7-11eb-950b-cf93e55d5f3d.png)

**Comment by lemmingDev** [comment]
I have asked around. IF I can get it working, I'll update the library

**Comment by beastdjw** [comment]
https://www.youtube.com/watch?v=nrT7WXFEEZI
