### ISSUE TITLE
Support Force Feedback

### ISSUE THREAD

**Issue by idrislaode** [lemmingDev/ESP32-BLE-Gamepad#29]
Can support force feedback?

**Comment by lemmingDev** [comment]
Unfortunately, not at the moment

**Comment by LeeNX** [comment]
@lemmingDev what could get you interested in at least haptic feedback? I see that my PS4 controller, which I use as a reference and testing, I found that Chrome on OSX has basic haptic support, playing https://tomayac.github.io/chrome-dino-gamepad/ vibrations was working when falling, which is awesome!

**Comment by lemmingDev** [comment]
Interesting.

If anyone ever works out how to add force feedback to ESP32/BLE Gamepad/Arduino, I'll be more than happy to add it to this library.
