### ISSUE TITLE
Windows does not see ESP32 BLE Gamepad

### ISSUE THREAD

**Issue by beastdjw** [lemmingDev/ESP32-BLE-Gamepad#30]
When I do a Add Bluetooth or other device in Windows 10, it does not see this device. In Linux and Android it sees this device. My bluetooth adapter is a 4.0 usb adapter. Any ideas?

**Comment by lemmingDev** [comment]
Hi

Sorry - no idea

Is viewable on every Windows 10 computer (with BT 4.0 or above) I've ever tried

You have to use the top option

![image](https://user-images.githubusercontent.com/15526971/100734831-fd197f00-341b-11eb-97fc-fc9dc6b11cc8.png)

**Comment by uecken** [comment]
In Windows 10, I think there are two reasons for not connecting.

1. Bluetooth driver may have bad state.
  Driver may have bad state. Uninstall the driver(ex: intell wireless bluetooth) and reboot Bluetooth Device. I use Bluetooth USB Dongle. 
![Uninstall Driver](https://user-images.githubusercontent.com/5786149/100761128-e2540400-3435-11eb-9c64-e7f1cf11cc82.png)

2. The Bluetooth module does not support GATT.

**Comment by beastdjw** [comment]
Thx for helping! I think my usb bluetooth adapter is not really 4.0 and is not really ble although its mentioned in the description. I've read on the amazon webstore a lot of comments about those usb bt adapters which are not really 4.0. Now I bought a new one (5.0), and will get it in a few days. I will test it and report it here if its functioning.

**Comment by beastdjw** [comment]
I have ordered: https://www.amazon.de/-/nl/gp/product/B08K4GZLMH/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
and can confirm the ESP32 BLE Gamepad sofware is now working. So watch out! Buy a good bluetooth ble adapter!

Thanks for helping me!
p.s. I am working at a bluetooth ble buttonbox for a racesteer. I will post this repository soon.

**Comment by lemmingDev** [comment]
Good to hear

Have fun with the library
