### ISSUE TITLE
How do i go about setting my HID report map?

### ISSUE THREAD

**Issue by Terramoto** [lemmingDev/ESP32-BLE-Gamepad#33]
Hello,

I'm trying to have my flight stick show up in windows game controllers, i've manage to have it connect to windows and display the device but no  configuration is available. I have no idea how/where to setup the HID descriptor report map.

**Comment by LeeNX** [comment]
I think you need to update the library to make changes to the HID descriptor, the default is basically what I have posted below.
```
leet-mbp:build leet$ ./sdl2-jstest -l
Found 1 joystick(s)

Joystick Name:     'Manufacturer LeeNX Device Name'
Joystick GUID:     0300000002e50000abcd000001100000
Joystick Number:    0
Number of Axes:     6
Number of Buttons: 32
Number of Hats:     2
Number of Balls:    0
GameControllerConfig:
  missing (see 'gamecontrollerdb.txt' or SDL_GAMECONTROLLERCONFIG)
```
There has been a suggestion update the library to be more dynamic or suggest that it should be easy to override the default, but I will admit I don't know how to do either.

**Comment by lemmingDev** [comment]
Are you trying to create a custom controller by modifying the BleGamepad.cpp and BleGamepad.h files?

**Comment by lemmingDev** [comment]
Happy to help if you let me know what you're trying to do.

If not, I'll close the issue

**Comment by lemmingDev** [comment]
Will close due to no response. 

Feel free to create another issue if you need help
