### ISSUE TITLE
Changing controller name?

### ISSUE THREAD

**Issue by chemic** [lemmingDev/ESP32-BLE-Gamepad#35]
Is it possible to change the name of the controller anyhow?
![controller-name](https://user-images.githubusercontent.com/3408491/103466549-d322e780-4d4e-11eb-9871-9310fffa9f7d.png)

Thanks for the great library.. it made it to my simracing custom Ferrari 488 wheel 💯

**Comment by lemmingDev** [comment]
Hi

I'm not sure how.
I have asked around...
https://github.com/nkolban/esp32-snippets/issues/230#issuecomment-735285688

**Comment by lishuai199502** [comment]
Hi
Maybe these pages can help
https://learn.microsoft.com/en-us/answers/questions/401236/hidd-getproductstring-with-ble-hid-device.html
https://learn.microsoft.com/en-us/answers/questions/406840/hidd-getproductstring-with-classic-bluetooth-devic.html
https://learn.microsoft.com/zh-CN/windows-hardware/drivers/ddi/hidsdi/nf-hidsdi-hidd_getproductstring
It seems like the ble not support，but classic bt can set the Service Name in SDP protocol.
