### ISSUE TITLE
Esp32 battery show in Android Phone

### ISSUE THREAD

**Issue by lxzcl** [lemmingDev/ESP32-BLE-Gamepad#46]
There is no battery icon in the Android phone, but it is displayed normally in win10.I just touched this recently.

oh my low English...

**Comment by LeeNX** [comment]
I have a few deevices that don't show up in the Android status bar with battery details and have used the Android App ```BatON``` as can be seen in the following comment - https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/36#issuecomment-755169362. 
  
Hope that helps.

**Comment by lxzcl** [comment]
Bluetooth hardware version seems too low For Esp32, thank you for your help
