### ISSUE TITLE
constantly getting events, without user input

### ISSUE THREAD

**Issue by impatience-cmd** [lemmingDev/ESP32-BLE-Gamepad#49]
hi,

first of all, i'm kind of new, to how HID devices operate, but i'm willing to read more on those

i was able to get very far with my project, 
and the user input translates very well in various monitoring apps (windows10 gaming controller properties, joysticktest_092.exe application, and gamepadviewer.com)

but as soon as i jump into an emulator program, i get constant input:
sometimes it's pressing "down" (may be Dpad or analog command, or a button?!) constantly/repeatedly
^but this is NOT visible in the monitoring apps i mentioned.

i tried looking around in the library files, but i couldn't find something like "default send"

also it doesn't seem to be a certain button, like button1, or dpad etc.
it's just controller name, and a space; like this "Joypad "

but it gets received repeatedly by the emulator program
(and it seems to me, this background command is somehow blocking my ability to use my buttons, to interact with the emulation)

i haven't tested it on android, but will these days

i'm very thankful this library, it's great, and i got good results for my controller after a few hours, thanks!!

P.S.: is there an ability, to disable certain instances like "slider1, slider2" etc., since i don't need those, and my thought here is, can this probably somehow make the Bluetooth-"Bus" a little bit lighter, and less loaded with unused data?! since from the 64bit value, it seems with the ble-report, i always send all instances, that were created, and i thought they are send serially, so a smaller variable could means faster interaction?!?

thank you, if you can find time to respond

**Comment by lemmingDev** [comment]
Hi

Can you please tell me the name of an emulator you're having trouble with so I can test it out?

As for an option with less features,  you could try out version 1.6.
https://github.com/lemmingDev/ESP32-BLE-Gamepad/releases/tag/0.1.6 
It doesn't have the sliders and has a reduced number of buttons

**Comment by impatience-cmd** [comment]
the emulators are 'retroarch' and 'virtual boy'

in virtual boy the mapping was constantly taken over by this default repeatedly sending, so i wasn't able to map the controller
in retroarch, it was a better, i was able to map the controller, but still in-game the button event was received by the game


i also did a short test with the example sketch 'multiple buttons', but it also appeared there, the character constantly walks down in gb files and the menu keeps rotating, as if i would be holding a down dpad/or control stick in z64 files


should i add the code?

**Comment by impatience-cmd** [comment]
it also appeared, with all button press, setHat etc. disabled

might it be in the bluetooth server? (while it's connected)
i would like to try to troubleshoot myself, but my knowledge is not enough
i might try to read some more on it, and keep updating new finds, 

thank you so far! :)

**Comment by impatience-cmd** [comment]
another update:
tested on android - successfully.

the gamepad worked without issues on my android device

while scrolling through the settings of an app, that monitors gamepad input, i saw a checkbox: that pointed towards status/ID messages, something like: ~"ignore status ID messages",
the checkbox was true


so my question as of right now is:
- within the library, can i disable constant status commands/messages, the bluetooth device sends (~while connected?)
- if not so, would it be an issue of my windows10 laptop needing to ignore those commands, and NOT pass them on, to the emulator programs, as it does right now?

from my little 2 year experience on arduino so far, my feeling says, it might be able to disable these messages/commands withing the library (i stumbled onto something like "bluetooth server", that the device (ESP32) creates), although i don't know for sure

my knowledge about BLE protocool (HID) is not deep enough to judge upon that - what do you think?

**Comment by lemmingDev** [comment]
A couple of suggestions:

If it's not already, set your Core Debug Level to None

![image](https://user-images.githubusercontent.com/15526971/108635478-4d5c2680-74cb-11eb-91c3-aa74719ec852.png)

If that doesn't work, are you aware that there is another version of the gamepad library I maintain that uses the new NimBLE server instead of the default one?

It's more optimised, is updated regularly, more efficient and may just solver your problem.

Delete the current gamepad library from your libraries folder
Download and install the alternate gamepad library here: https://github.com/lemmingDev/ESP32-BLE-Gamepad/tree/NimBLE
You'll also need to have this library installed: https://github.com/h2zero/NimBLE-Arduino

Let me know how you go

**Comment by lemmingDev** [comment]
Send your code through if you're stiff having issues...

**Comment by impatience-cmd** [comment]
i tried your options, the issue still occurs.

how did your testing go? (quoted below):
> Hi
> 
> Can you please tell me the name of an emulator you're having trouble with so I can test it out?
> 
> As for an option with less features, you could try out version 1.6.
> https://github.com/lemmingDev/ESP32-BLE-Gamepad/releases/tag/0.1.6
> It doesn't have the sliders and has a reduced number of buttons

(1)
as far as example code goes, i'm using you example library, with digitalRead and != if state has changed from the blink sketch example from arduino ide; i commented out all serial monitor stuff, and also the debug level was none

(2)
version 1.6. did not work at all

(3)
using the NimBLE build, as you suggested didn't change anything.

i'm still getting constant events as stated in my first post.

**Comment by lemmingDev** [comment]
I tested with Retroarch and I was unable to reproduce the issue.

Are you using input pullups on your buttons? 

If you'd like further support, can you please provide your full code and the core and game you are trying to use in Retroarch.

Also, when you say Virtual Boy, I'm not sure what you mean. Can you link me to the specific emulator?

Thanks

**Comment by impatience-cmd** [comment]
yes the pins were with internal pullups

since the issue occured with the original example sketches, with commented out serial monitor, and also commented out functions: buttonpress, setAxes etc.,
my guess is that the commands are coming from somewhere within the library structure (maybe BT server), since they appear with the device idle (with the example sketch)

regarding the emulator: 
my bad, the emulator is called: "visual boy advance" - when trying to assign buttons (within the menu under 'joypad' (their name for gamepad)), the ghost command takes place repeatedly, and blocks button assignments (quickly overrides assignments). Usually an assignment looks something like "Joy 1 Button 1", but in the case of the idle command it's only "Joy 1 " (repeatedly sent).

link to the emulator:
http://www.emulator-zone.com/doc.php/gba/vboyadvance.html


checking again, in retroarch:
the game "wario blast featuring bomberman" (core: TGB Dual), the character still walks down all the time


another thought i had:
could it be my hardware? i have a esp32 (wroom) clone from ebay


for my project it's ok to shrink it to android, (it works fine there!), the idle command appears under windows only; i was hoping i could find the source of the command, but i'll reduce the bluetooth gamepad to android, and as for windows, i'll use my functioning build with a leonardo under USB

**Comment by lemmingDev** [comment]
Hi

Mapping the buttons in virtualboy advance works perfectly fine for me.

Please post your complete code so I can check it for problems

**Comment by impatience-cmd** [comment]
#include <BleGamepad.h>   // https://github.com/lemmingDev/ESP32-BLE-Gamepad



//how many buttons and potis?
#define button_amount 19               //13 button (digitalPin in,);
         //^differentiate between: arduino_button_amount = 13, and joystick_button_amount = arduino_button_amount - 4(dpad buttons)
         
#define analogstick_poti_amount 4     //4 analogRead in's for the sticks (left_x(A0); left_y(A1); right_x(A2); right_y(A3));

#define input_pins_amount 23   // actually only 20 -- buttons+analogReads
         //^calculate input_pins from: arduino_button_amount(9)+analogstick_poti_amount(4) = 13



BleGamepad bleGamepad;



int previousButton1State = HIGH;




byte input_pins[button_amount] = {15, 13, 2, 16, 4, 2, 19, 21, 22, 23, 5, 18, 2, 17, 2, 14, 27, 26, 25};
                                       //^D2 will be always low
//free pin; D2(OUTPUT only!)
//D12 free input


//flags for all states of n
bool change_n__flag_array[input_pins_amount] = {};     //21 positions

//button state array
bool button_n__last_state[button_amount] = {};



////STATE if analog readout
//poti ~pseudo-array(manual) for updating/storing the analogReads (faster, if it's only done once every n)
uint16_t state_A0 = 1865;       //4095/2;       //16-bit, for 0..4095(==12-bit; 12-bit ADC in ESP32)            //8-bit only 255states, 12-bit variable doesn't exist.
uint16_t state_A1 = 1865;       //4095/2;
uint16_t state_A2 = 1865;       //4095/2;
uint16_t state_A3 = 1865;       //4095/2;

uint16_t state_A0_previous;
uint16_t state_A1_previous;
uint16_t state_A2_previous;
uint16_t state_A3_previous;

int16_t state_A0_signedInt;
int16_t state_A1_signedInt;
int16_t state_A2_signedInt;
int16_t state_A3_signedInt;

int16_t state_A0_signedInt_previous;
int16_t state_A1_signedInt_previous;
int16_t state_A2_signedInt_previous;
int16_t state_A3_signedInt_previous;



//definitions for DPad (~dictionary)
#define dpad_right 3
#define dpad_left 7
#define dpad_down 5
#define dpad_up 1

#define dpad_right_up 2
#define dpad_left_up 8
#define dpad_right_down 4
#define dpad_left_down 6

#define dpad_center 0




//defining the n==x states for later easy use, and re-mapability of 'right', 'down', 'left', 'up'
  //Dpad button / which case for n
#define right 15   //11
#define left  16   //12
#define down  17   //13
#define up  18     //14



//counter
byte n;




//laziness timestamp (~debounce)
unsigned long timestamp_last_report;



//center state flag for dpad to prevent repetitive sending:
bool center_state_flag = 0;


unsigned long increment_;


uint16_t analog_noise_threshold = 180;  //good value:130  //values tried: 305, 200(too much ghosting); last value:310


bool report_flag = 0;



uint32_t change_flag_array;
uint32_t change_flag_array_previous;

uint32_t state_flag_array;
uint32_t state_flag_array_previous;





void setup() 
{
 // Serial.begin(115200);

  //sweep over digitalPins to make them input_pullup
 for(n=0;n<button_amount;n++){          //0..14 (n==15, ->break)
  pinMode(input_pins[n], INPUT_PULLUP);          //start with D4..through Dn_max; 4+button_amount-1
 }


 //built in LED for bluetooth connected:
 pinMode(2, OUTPUT);
 digitalWrite(2, HIGH);
 

  bleGamepad.begin(false);            //nothing means default autosendreport (~flush) to 1 (true), a send report will be created withing buttonpress or buttonrelease
         //^test auto report on or off (maybe autoreport false makes sense, with 15 buttons an 4 analog ADCs, because the data stream of updating EVERYTHING all the time, takes too much un-necessary bandwidth?




  //Serial.println("Starting BLE work!");
}




void loop() {

/*
 * Serial monitor checking for the CHANGED-arrays
 * 
for(n=0;n<input_pins_amount;n++){                 //21 positions for n, 21 states, because input_pins_amount is 21 here
  bitWrite(change_flag_array, n, change_n__flag_array[n]);  
  //bitWrite(state_flag_array, n, button_n__last_state[n]);                                 
} 

for(n=0;n<button_amount;n++){                 //21 positions for n, 21 states, because input_pins_amount is 21 here
  //bitWrite(change_flag_array, n, change_n__flag_array[n]);  
  bitWrite(state_flag_array, n, button_n__last_state[n]);  
                                       
} 



if(state_flag_array != state_flag_array_previous){
  Serial.println();
} else if (change_flag_array != change_flag_array_previous) {
  Serial.println();
  }


if(change_flag_array != change_flag_array_previous){
Serial.print(change_flag_array, BIN);
Serial.print(" ");
change_flag_array_previous = change_flag_array;
}

if(state_flag_array != state_flag_array_previous){
Serial.print(state_flag_array, BIN);
Serial.print(" ");
state_flag_array_previous = state_flag_array;
}
*
*
*end of serial monitor checking
*/



//
///START of actual routine:
//
//cycle through all input pins, and get states/values         //n goes from 0..8 
for(n=0;n<input_pins_amount;n++){                 //21 positions for n, 21 states, because input_pins_amount is 21 here
  
  detect_input_pin_states(n);
                        
                           //change_n__flag_array[n] = 0;
 } //breaks for n == 19 (input_pins_amount)



       
if (micros()-timestamp_last_report > 500) {

   for(n=0;n<input_pins_amount;n++){   
     execute_commands(n);    //lower flag is withing the execute commands function!
   }
  
  if (report_flag){
    bleGamepad.sendReport();    //flag send report (every serial print, that executes now, can raise the report flag!
    report_flag = 0;
  }
  

  timestamp_last_report = micros();
 }


}


void detect_input_pin_states(byte n) {
  
if (change_n__flag_array[n] == 0){
  
  //deciding if-loop, if this n is button or poti:
    //ab 9 geht er hier rein
    if(n>(button_amount-1)) {      //button_amount-1 = 16 in this instance
          //same code for every n==16,17,18,19
          if (n==19) {
              //state_A0 = analogRead(33);  //make ReadOut
              state_A0  = 0.7*state_A0 + 0.3*analogRead(33);
              //analog Multiplexing: check if difference between the two states is greater than standard noise of 1 [direction of - and + doesn't matter because of abs()]
              if (abs(state_A0 - state_A0_previous)>analog_noise_threshold) {
                //Serial.println(state_A0);
                change_n__flag_array[n] = 1;  //raise flag if so, and
                state_A0_previous = state_A0; //update storing, so it only comes once
              }
          }
          if (n==20) {
              //state_A0 = analogRead(33);  //make ReadOut
              state_A1  = 0.7*state_A1 + 0.3*analogRead(32);
              //analog Multiplexing: check if difference between the two states is greater than standard noise of 1 [direction of - and + doesn't matter because of abs()]
              if (abs(state_A1 - state_A1_previous)>analog_noise_threshold) {
                //Serial.println(state_A1);
                change_n__flag_array[n] = 1;  //raise flag if so, and
                state_A1_previous = state_A1; //update storing, so it only comes once
              }
          }
          if (n==21) {
              //state_A2 = analogRead(35);  //make ReadOut
              state_A2  = 0.7*state_A2 + 0.3*analogRead(35);
              //analog Multiplexing: check if difference between the two states is greater than standard noise of 1 [direction of - and + doesn't matter because of abs()]
              if (abs(state_A2- state_A2_previous)>analog_noise_threshold) {
                //Serial.println(state_A2);
                change_n__flag_array[n] = 1;  //raise flag if so, and
                state_A2_previous = state_A2; //update storing, so it only comes once
              }
          }
          if (n==22) {
              //state_A3 = analogRead(34);  //make ReadOut
              state_A3  = 0.7*state_A3 + 0.3*analogRead(34);
              //analog Multiplexing: check if difference between the two states is greater than standard noise of 1 [direction of - and + doesn't matter because of abs()]
              if (abs(state_A3 - state_A3_previous)>analog_noise_threshold) {
                //Serial.println(state_A3);
                change_n__flag_array[n] = 1;  //raise flag if so, and
                state_A3_previous = state_A3; //update storing, so it only comes once
              }
          }          
    } //end of if of detection loop (the half for analog_Reads/potis
    else if(n < 19){    //bis n==16 geht er hier rein [n<17]
      //button detection loop
               //n=0         //n=0            //input_pins[n] == the referred GPIO pin (->chaotic numbering)
      if (button_n__last_state[n] != !digitalRead(input_pins[n])){     //button pulls pin low; pull-up pulls back, FALL(button), RISE(pull-up) -->that's why LED goes back low, and analogRead doesn't!
         button_n__last_state[n] = !digitalRead(input_pins[n]);         //store changed value for later purposes
         change_n__flag_array[n] = 1;                     //[0] first array position --> ~ch1
         //Serial.print("button detected: ");
         //Serial.println(n);
      }
    }

 }
}

void execute_commands(byte n) {
  ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    //execution loop BUTTONs (not DPAD)
    if(change_n__flag_array[n] == 1 && n < 15){              //n < 17, n==0..16 means it is a button
      
      report_flag = 1;
      
     ///////////////////       
     //NOT-DPAD button execution routine:
     ///////////////////
      if (n >= 0 && n <= 14 && button_n__last_state[n] == 1){   //EXCLUDING(!) Dpad n==15,16,17,18
       bleGamepad.press(pow(2, n));     //n==0: 2^0 => 1;
       //Serial.print("button press sent: ");
       //Serial.println(n);
      }
       else if (n >= 0 && n <= 14 && button_n__last_state[n] == 0){   //EXCLUDING(!) Dpad n==13,14,15,16
        bleGamepad.release(pow(2, n));     //n==0: 2^0 => 1;
        //Serial.print("button release sent: ");
        //Serial.println(n);
       }
    //change_n__flag_array[n] = 0; //empty flags for n == 0..10
    change_n__flag_array[0] = 0; //empty flags for n == 0
    change_n__flag_array[1] = 0; //empty flags for n == 1
    change_n__flag_array[2] = 0; //empty flags for n == 2
    change_n__flag_array[3] = 0; //empty flags for n == 3
    change_n__flag_array[4] = 0; //empty flags for n == 4
    change_n__flag_array[5] = 0; //empty flags for n == 5
    change_n__flag_array[6] = 0; //empty flags for n == 6
    change_n__flag_array[7] = 0; //empty flags for n == 7
    change_n__flag_array[8] = 0; //empty flags for n == 8
    change_n__flag_array[9] = 0; //empty flags for n == 9
    change_n__flag_array[10] = 0; //empty flags for n == 10
    change_n__flag_array[11] = 0; //empty flags for n == 11
    change_n__flag_array[12] = 0; //empty flags for n == 12
    change_n__flag_array[13] = 0; //empty flags for n == 13
    change_n__flag_array[14] = 0; //empty flags for n == 14
    }

         
//DPad stuff
    if(change_n__flag_array[n] == 1 && n > 14 && n < 19){              //n < 19, n==0..18 means it is a button

      report_flag = 1;

      
//bleGamepad.setHat(char); unsigned
 ///////////////////       
     //ALL DPAD (Hat Switch) execution routines:
     ///////////////////
       //right == true                                       down == false                       up == false
      if (button_n__last_state[right] == 1 && button_n__last_state[down] == 0 && button_n__last_state[up] == 0) { 
        //bleGamepad.setHat1(dpad_right);
        
        bleGamepad.setLeftThumb(32767, 0);
        //bleGamepad.setX(0);
        //bleGamepad.setY(2048);
        
        //Serial.println("dpad set to right");
        center_state_flag = 0;
      }  
      //  else if(button_n__last_state[5] == 0){
      //  Joystick.setHatSwitch(0, dpad_center);
       // }
        

      //down == true                                           left == false                            right == false
      if (button_n__last_state[down] == 1 && button_n__last_state[left] == 0 && button_n__last_state[right] == 0) { 
        //bleGamepad.setHat1(dpad_down);
        
        bleGamepad.setLeftThumb(0, 32767);
        //bleGamepad.setX(2048);
        //bleGamepad.setY(0);
        
        //Serial.println("dpad set to down");
        center_state_flag = 0;
      }
      //  else if(button_n__last_state[6] == 0){
      //  Joystick.setHatSwitch(0, dpad_center);
      // }



      //up == true                                        left == false                        right == false
      if (button_n__last_state[up] == 1 && button_n__last_state[left] == 0 && button_n__last_state[right] == 0) { 
        //bleGamepad.setHat1(dpad_up);
        

        bleGamepad.setLeftThumb(0, -32767);
        //bleGamepad.setX(2048);
        //bleGamepad.setY(4095);
        
        //Serial.println("dpad set to up");
        center_state_flag = 0;
      }
      //  else if(button_n__last_state[7] == 0){
      //  Joystick.setHatSwitch(0, dpad_center);
      //  }


      //left == true                                          down == false                              up == false
      if (button_n__last_state[left] == 1 && button_n__last_state[down] == 0 && button_n__last_state[up] == 0) { 
        //bleGamepad.setHat1(dpad_left);
        
        bleGamepad.setLeftThumb(-32767, 0);
        //bleGamepad.setX(4095);
        //bleGamepad.setY(2048);
        
        //Serial.println("dpad set to left");
        center_state_flag = 0;
      }
      //  else if(button_n__last_state[8] == 0){
      //  Joystick.setHatSwitch(0, dpad_center);
      //  }


  
     //schraege: right == true                              down == true                        up == false
     if(button_n__last_state[right] == 1 && button_n__last_state[down] == 1 && button_n__last_state[up] == 0){
        //bleGamepad.setHat1(dpad_right_down);
        
        bleGamepad.setLeftThumb(32767, 32767);
        //bleGamepad.setX(400);
        //bleGamepad.setY(0);
        
        //Serial.println("dpad set to right_down");
        center_state_flag = 0;
        }
        //else if(button_n__last_state[5] == 0 && button_n__last_state[6] == 0 && button_n__last_state[7] == 0){
        //Joystick.setHatSwitch(0, dpad_center);
        //}



     //schraege:   right == true                            up == true                         down == false
     if(button_n__last_state[right] == 1 && button_n__last_state[up] == 1 && button_n__last_state[down] == 0){
        //bleGamepad.setHat1(dpad_right_up);
        
        bleGamepad.setLeftThumb(32767, -32767);
        //bleGamepad.setX(400);
        //bleGamepad.setY(4095);
        
        //Serial.println("dpad set to right_up");
        center_state_flag = 0;
        }
        //else if(button_n__last_state[5] == 0 && button_n__last_state[6] == 0 && button_n__last_state[7] == 0){
        //Joystick.setHatSwitch(0, dpad_center);
        //}


 
     //schraege:   left == true                          up == true                         down == false
      if (button_n__last_state[left] == 1 && button_n__last_state[up] == 1 && button_n__last_state[down] == 0) { 
        //bleGamepad.setHat1(dpad_left_up);
        
        bleGamepad.setLeftThumb(-32767, -32767);
        //bleGamepad.setX(3500);
        //bleGamepad.setY(4095);
        
        //Serial.println("dpad set to left_up");
        center_state_flag = 0;
        }


     //schraege:   left == true                          down == true                        up == false
      if (button_n__last_state[left] == 1 && button_n__last_state[down] == 1 && button_n__last_state[up] == 0) { 
        //bleGamepad.setHat1(dpad_left_down);
        
        bleGamepad.setLeftThumb(-32767, 32767);
        //bleGamepad.setX(3500);
        //bleGamepad.setY(0);

        //Serial.println("dpad set to left_down");
        center_state_flag = 0;
        }


      //CENTER: all == false
      if(button_n__last_state[right] == 0 && button_n__last_state[left] == 0 && button_n__last_state[down] == 0 && button_n__last_state[up] == 0 && center_state_flag == 0){
        //bleGamepad.setHat1(dpad_center);
        
        bleGamepad.setLeftThumb(0, 0);
        //bleGamepad.setX(2048);
        //bleGamepad.setY(2048);
        
        //Serial.println("dpad set to center");
        center_state_flag = 1;
        }
        
   // change_n__flag_array[n] = 0; //empty flags for n == 11..14
    change_n__flag_array[15] = 0; //empty flags for n == 15
    change_n__flag_array[16] = 0; //empty flags for n == 16
    change_n__flag_array[17] = 0; //empty flags for n == 17
    change_n__flag_array[18] = 0; //empty flags for n == 18
    }



////////////////////////////////////////////////////////////////////////////////
    //execution loop ANALOGreads (4 potis)

    if(change_n__flag_array[n] == 1 && n > 18){              //n > 18, means it is a poti

      report_flag = 1;
      
      //Serial.print("n:");
      //Serial.println(n);
       if(n==19){
         state_A0_signedInt = map(state_A0, 4095, 0, -32767, 32767);       //i do remember the 0 counts to the positives!! (because it's unsigned!)
         //Joystick.setXAxis(state_A0_signedInt);        // -127 .. 0 .. 127   a signed int for position 

           bleGamepad.setX(state_A0_signedInt);
           //bleGamepad.setLeftThumb(state_A0_signedInt, state_A1_signedInt);

           //Serial.print("state_A0_signedInt: ");
           //Serial.println(state_A0_signedInt);                                                                   
       }
       if(n==20){
         state_A1_signedInt = map(state_A1, 4095, 0, -32767, 32767);
         //Joystick.setYAxis(state_A1_signedInt);       

           bleGamepad.setY(state_A1_signedInt);
           //bleGamepad.setLeftThumb(state_A0_signedInt, state_A1_signedInt);

          
           //Serial.print("state_A1_signedInt: ");
           //Serial.println(state_A1_signedInt);           
        // }          
       }
       if(n==21){    //left and right movement of the hama right stick
         state_A2_signedInt = map(state_A2, 4095, 0, -32767, 32767);
         //Joystick.setZAxis(state_A2_signedInt);

         bleGamepad.setZ(state_A2_signedInt);
         //bleGamepad.setRightThumb(state_A2_signedInt, state_A3_signedInt);

          
           //Serial.print("state_A2_signedInt: ");
           //Serial.println(state_A2_signedInt);                           
       }
       if(n==22){    //up and down movement of the hama right stick   [IT'S INVERTED BY HAMA] moving down caused(?) -Y
         state_A3_signedInt = map(state_A3, 4095, 0, -32767, 32767);
         //Joystick.setRzAxis(state_A3_signedInt);

           bleGamepad.setRZ(state_A3_signedInt);
           //bleGamepad.setRightThumb(state_A2_signedInt, state_A3_signedInt);
          
           //Serial.print("state_A3_signedInt: ");
           //Serial.println(state_A3_signedInt);                   
       }
    
    change_n__flag_array[19] = 0; //empty flags for n == 19
    change_n__flag_array[20] = 0; //empty flags for n == 20
    change_n__flag_array[21] = 0; //empty flags for n == 21
    change_n__flag_array[22] = 0; //empty flags for n == 22
    }  


}

//END OF CODE

**Comment by impatience-cmd** [comment]
i tried posting with < >
but my code it didn't catch it correctly

so here's the file directly as .ino:
https://drive.google.com/file/d/1haqXyhtnJn5gfhDoP5ac7Rp4-5_Lci7p/view?usp=sharing

**Comment by lemmingDev** [comment]
Wow

There is a lot going on in your code.

May I suggest that you start a fresh sketch with just the button code only (no analogs, hats, sliders etc) and confirm that there are no extra events.

If that works, then slowly add one feature at a time until you find the culprit.

FYI, I am working on a new version of the library that has a customisable HID where you only enable the features you want. 

It currently supports any number of buttons from 0 to 64, plus any combination of axes out of X, Y, Z rZ, rX and rY

When I get motivated, I'll finish adding the hats, sliders and even some racing simulator controls.

**Comment by impatience-cmd** [comment]
thank you for verifying, and trying to recreate the issue i had.

on all my other projects in arduino i was able to find the cause of the issue;
this is the first arduino sketch, where i somewhat "blamed it on the library";

because in the example sketches, even with disabling the button.press() etc. commands, (and leaving .begin(false) on, the issue still appeared;

the code that i made works fine under a leonardo over usb. so i took from that build, adjusted it, towards your library commands/functions, and then troubleshooted it with the serial.monitor

i still think my code should be fine,
since the gamepad-monitoring apps do **not** receive a permament 'hold down some button'; and disabling all the button events etc. still caused the issue... that's what's mysterious about it to me.

but anyway thank you for your time, and thoughts; since android doesn't face the issue i can still find a good use for the amount of time&work put in.

it's a good library thank you :)
and i'm also hyped about the tailoring the elements (less buttons etc.)
if you like, you can close this issue

**Comment by lemmingDev** [comment]
Have you tried it on another Windows machine, another Bluetooth dongle or another ESP32 board?
I can't seem to reproduce the issue at all.

Your code seemed a bit weird with pin 2 being used for an LED output, and then used again repeatedly for different button inputs.

But removing your code from the equation and just using the MultipleButtonsDebounce example for testing, I am able to open the two emulators and map the buttons without issue. There's no "phantom" presses or the like.

So, let me know if you have another Windows machine to test with. Fire up either the SingleButtonDebounce or MultipleButtonsDebounce sketch (make sure to edit the pin variables to suit) and test for me

**Comment by lemmingDev** [comment]
Try out this new test version
https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/54#issue-849162930

It allows you to enable only the features your controller is using
