### ISSUE TITLE
Encoder interrupts mess with send report?

### ISSUE THREAD

**Issue by lospeq** [lemmingDev/ESP32-BLE-Gamepad#51]
I have a rotary encoder working with ESP32Encoder library and by itself it works fine. If a turn was made, I just register it as a press on one of the two designated buttons and then release it after 20 ms. 

In the main loop I constantly check if there was a change in the global gamepad state, and if there was - I call sendReport() manually after bleSend was called. Logging always outputs correct values - press report, 20ms, release report.

If I rotate the encoder with a normal "mouse scroll" speed (not sure how to define it, not slow not fast) some presses get lost but it's more or less okay. If I rotate super fast, I assume hid reporting gets overloaded and only a fraction of presses get past - which is to be expected so it's fine as well. 
But if I start rotating slowly (both super slow and just more leisurely) - more than half of reports won't reach the pc. After trying different timings I started suspecting that maybe if one rotation cycle is going for some time (~20-80ms?) then perhaps some encoder interrupts are firing all throughout this duration and sendReport() fails? 

Or is there something I'm missing or is mistaken about?

Some code snippets:
```
#define ENCODER_CHECK_INTERVAL 20

struct Encoder
{
  int curCount = 0;
  int ids[2];
  ESP32Encoder encoderLogic;
  unsigned int lastChange = 0;

  Encoder(int id1, int id2, byte pin1, byte pin2)
  {
    ids[0] = id1;
    ids[1] = id2;

    encoderLogic.attachHalfQuad(pin1, pin2);
  }

  void check(State &state)
  {
    unsigned int cur = millis();
    if (cur - lastChange < ENCODER_CHECK_INTERVAL)
    {
      return;
    }

    int count = (int32_t)encoderLogic.getCount();

    state.encoder[0] = false;
    state.encoder[1] = false;

    if (count != curCount)
    {
      lastChange = cur;
      state.encoder[count > curCount ? 1 : 0] = true;
      curCount = count;

      Serial.println("Encoder count = " + String(count) + " " + lastChange + " " + millis());
    }
  }

  void bleSend(State &state)
  {
    Serial.println("send encoder " + String(state.encoder[0]) + " " + String(state.encoder[1]) + " " + lastChange + " " + millis());
    for (short i = 0; i < 2; i++)
    {
      state.encoder[i] ? bleGamepad.press(ids[i]) : bleGamepad.release(ids[i]);
    }
  }
};

encoder(BUTTON_11, BUTTON_12, ENCODER_PIN1, ENCODER_PIN2);
```

**Comment by lemmingDev** [comment]
Hi

Unfortunately I've never used interrupts and am not sure what the problem would be.

I haven't used the library in scenarios past flappy bird, so am not sure of the actual real-world performance, although feedback suggests that it works pretty well.
