### ISSUE TITLE
New version with configurable HID descriptor

### ISSUE THREAD

**Issue by lemmingDev** [lemmingDev/ESP32-BLE-Gamepad#54]
I have created a version of the library with a configurable HID descriptor

You can choose to enable/disable:

- 0 ~ 128 buttons
- 0 ~ 4 hat switches
- x, y, z, rZ, rX, rY axes (any combination)
- 0 ~ 2 sliders
- simulation controls (rudder, throttle, accelerator, brake, steering) (any combination)

You can also set the controller type between joystick, gamepad and multi-axis

Depending on your OS, only certain combinations/amounts may be seen

This version also uses the new and improved NimBLE library for efficiency

Haven't got around to updating all of the examples yet...

Contains much of the functionality from here:
https://github.com/MHeironimus/ArduinoJoystickLibrary/

Anyone keen to test it out?

**Comment by Johnbo100** [comment]
I would be happy to test it out

**Comment by lemmingDev** [comment]
OK - For anyone looking to try it

I have updated/added examples/readme to reflect new functionality

[ESP32-BLE-Gamepad.zip](https://github.com/lemmingDev/ESP32-BLE-Gamepad/files/6253300/ESP32-BLE-Gamepad.zip)

**Installation**
- Delete your old version
- Extract this new one to your libraries
- Make sure NimBLE is installed either through the libraries manager or from https://github.com/h2zero/NimBLE-Arduino
- Fire up/modify some example

Let me know how it goes

**Comment by FANHXIN** [comment]
Very good function
I'm willing to help test

**Comment by FANHXIN** [comment]
Enable RX true is actually displayed as RY

**Comment by FANHXIN** [comment]
Enable RZ true is actually displayed as RX

**Comment by FANHXIN** [comment]
Enable RY true is actually displayed as RZ

**Comment by lemmingDev** [comment]
Thanks for testing!

I have updated the post above with that fixed

The HID report was sent in the order x, y, z, rZ, rX, rY 
however
The HID descriptor was defined in the order x, y, z, rX, rY, rZ

They are now both correctly set in the order x, y, z, rZ, rX, rY 

Did you pick up anything else?

**Comment by FANHXIN** [comment]
At present, no other problems have been found, I will continue to test

**Comment by FANHXIN** [comment]
NimBLE-Arduino，What's the function of this? I am not using the library

**Comment by FANHXIN** [comment]
I would like to ask how to write the power monitoring code

I want to test it

**Comment by FANHXIN** [comment]
New library, test can connect, but the key, axis no response

**Comment by FANHXIN** [comment]
Is the value of rotation axis 32737 or 65474

map(potValue, 0, 4095, 65474, -65474);

**Comment by FANHXIN** [comment]
Same sketch, new library, axis no response

**Comment by FANHXIN** [comment]
The display is normal

**Comment by FANHXIN** [comment]
Single RX display will not work normally, but when RX RZ ry is turned on, RX will work

**Comment by FANHXIN** [comment]
I suggest checking the shaft. It seems that there is something wrong with the shaft
With the example z-axis, there is no reaction

**Comment by FANHXIN** [comment]
Test to me almost crazy, finally find the problem, ry open, but show as Rx

Open the shaft, even after normal operation, the shaft is not in the zero position, and then in the middle position

Oh, My God

**Comment by FANHXIN** [comment]
Even if the rotation axis works, it is not in the zero position

**Comment by LeeNX** [comment]
This is awesome! Thanks @lemmingDev ... Bummer, my Arduino IDE will not start on my Mac ... Why, cruel world!  
  
Is it possible to make a git branch tracking this work? I am going to track down another PC, so I can try and play with this new toy ...

**Comment by lemmingDev** [comment]
Hi

Some of your previous sketches will not work with this new version as ALL axes are mapped from -32767 to 32767, instead of previously where some mapped from 0 to 65k or so

**Comment by lemmingDev** [comment]
> NimBLE-Arduino，What's the function of this? I am not using the library

NimBLE is a library that has a new Bluetooth implementation

**Comment by lemmingDev** [comment]
> I would like to ask how to write the power monitoring code
> 
> I want to test it

You'll need to find out how to get the percentage from your battery using a voltage divider (some ESP32 have them on a certain pin, while others don't, and you need 2 resistors), and then you send that value to your OS using , for example:
````
bleGamepad.setBatteryLevel(50);
````
to set it to 50%

**Comment by lemmingDev** [comment]
> This is awesome! Thanks @lemmingDev ... Bummer, my Arduino IDE will not start on my Mac ... Why, cruel world!
> 
> Is it possible to make a git branch tracking this work? I am going to track down another PC, so I can try and play with this new toy ...

You could use a virtual machine or Bootcamp if you're desperate to try (assuming you don't have one on the new ARM Macs)

**Comment by lemmingDev** [comment]
> Single RX display will not work normally, but when RX RZ ry is turned on, RX will work

I will try to check this out when I get a chance, but in the meantime, are you trying to set this with a potentiometer, or just virtually in code?

If you're using a potentiometer, perhaps try another pin

**Comment by lemmingDev** [comment]
> Is it possible to make a git branch tracking this work? I am going to track down another PC, so I can try and play with this new toy ...

https://github.com/lemmingDev/ESP32-BLE-Gamepad/tree/NimBLE

**Comment by FANHXIN** [comment]
Rx is working，nice！

What's your new library

How to write a new button after pressing the button to realize the third button

**Comment by FANHXIN** [comment]
There is also a problem about the shaft. The shaft shakes very badly！

numberOfPotSamples，Set it higher. I don't know if it can be solved

**Comment by lemmingDev** [comment]
> Rx is working，nice！
> 
> What's your new library
> 
> How to write a new button after pressing the button to realize the third button

I don't understand the question

If you want to press a button, you simply need to use, for example:
```
bleGamepad.press(3);
```
or
```
bleGamepad.press(BUTTON_3);
```
Both do the same thing

Then to release the button:
```
bleGamepad.release(3);
```
or
```
bleGamepad.release(BUTTON_3);
```
If you disable auto reports, then you need to remember to call
```
bleGamepad.sendReport();
```
every time you want to update the gamepad

**Comment by FANHXIN** [comment]
Can your library be used with Bluetooth serial.h

**Comment by FANHXIN** [comment]
Or can you add Bluetooth serial port function

**Comment by FANHXIN** [comment]
Can your library be used with Bluetooth serial.h

Or can you add Bluetooth serial port function

**Comment by lemmingDev** [comment]
> Can your library be used with Bluetooth serial.h
> 
> Or can you add Bluetooth serial port function

I believe you can use BT Serial with it. Give it a shot

**Comment by FANHXIN** [comment]
It can display Bluetooth serial port and run your library perfectly at the same time

thx

**Comment by lemmingDev** [comment]
> There is also a problem about the shaft. The shaft shakes very badly！
> 
> numberOfPotSamples，Set it higher. I don't know if it can be solved

This is now to how noisy the analog reads are on the ESP32 and the (poor) quality of potentiometer hardware used.

Pretty sure it has nothing to do with the library as when you generate the values via code, it's very precise.

If you run the PotAsAxis sketch and view the serial output, you'll see what I mean.

Could the example sketch be improved to reduce the jitter --> Yes - certainly
Does the library need to be improved --> correct me if I'm wrong, but I don't think it does

**Comment by lemmingDev** [comment]
Oh - just realised you're probably trying to read 5V values.

ESP32 reads 0~3.3v, not 0~5v

So, make sure you are providing 3.3v from the ESP32 to the potentiometer instead of 5v

I just tried providing 5v to the potentiometer and the values were all over the place.
When I provided  3.3v, things were **much** better

Please provide feedback as to whether this was the issue you were having and whether it is now fixed

**Comment by FANHXIN** [comment]
Yes, I use 5V

I'm still testing

I need your help！
Help me add the sketch of Bluetooth serial port in your library

**Comment by lemmingDev** [comment]
Please try 3.3V to fix the potentiometer problem first.

Once that is fixed, we'll move on to the next issue

________________________________

**Comment by FANHXIN** [comment]
In fact, a good solution, in the potentiometer signal esp32, peripheral low-pass filtering, should be able to solve

**Comment by lemmingDev** [comment]
So, what information exactly are you trying to send over BT Serial?

Can you post the code you've been trying?

I have used BLE Mouse library and BT Serial at the same time before and it worked pretty well (a prototype IR lightgun I was working on)

**Comment by FANHXIN** [comment]
#include "BluetoothSerial.h"

#if !defined(CONFIG_BT_ENABLED) || !defined(CONFIG_BLUEDROID_ENABLED)
#error Bluetooth is not enabled! Please run `make menuconfig` to and enable it
#endif

BluetoothSerial SerialBT;

void setup() {
  Serial.begin(115200);
  SerialBT.begin("ESP32test"); //Bluetooth device name
  Serial.println("The device started, now you can pair it with bluetooth!");
}

void loop() {
  if (Serial.available()) {
    SerialBT.write(Serial.read());
  }
  if (SerialBT.available()) {
    Serial.write(SerialBT.read());
  }
  delay(20);
}

**Comment by FANHXIN** [comment]
This is the esp32 Bluetooth serial port, which becomes a serial port after adapting to the computer. You can communicate with the screen by using RX TX, but I don't know how to add it to your library and use it with buttons

**Comment by lemmingDev** [comment]
So, that sketch just takes information from the BT Serial and retransmits it over USB Serial.

Is that what you actually want to do, or do you want to do something else?

**Comment by FANHXIN** [comment]
Do you know simhub？

**Comment by lemmingDev** [comment]
Nope, but I have Google

**Comment by FANHXIN** [comment]
I want nexion to receive information through Bluetooth serial port, but I want to use your library at the same time

**Comment by lemmingDev** [comment]
What is nexion?

**Comment by lemmingDev** [comment]
So, you want the ESP32 to have a 9600 baud rate Classic Serial BT connection that just receives (or do you need it to send too?) information from some type of device?

And then what do you want to do with that information once received?

**Comment by FANHXIN** [comment]
Serial port screen

**Comment by FANHXIN** [comment]
I just need to receive, and the serial port screen will work after receiving

**Comment by FANHXIN** [comment]
Baud rate 115200

**Comment by lemmingDev** [comment]
I think Classic BT only receives at 9600.

Of course you can output that info to the USB Serial at 115200

**Comment by FANHXIN** [comment]
So I want you to help me finish it

**Comment by lemmingDev** [comment]
So, is nexion the name of the device you are creating with my library, or some other device?

Also, what device will be sending the ESP32 the BT Serial information? A PC?

**Comment by FANHXIN** [comment]
Just use the name of your library. It's a computer

**Comment by FANHXIN** [comment]
In simple terms, just like using 32u4's ArduinoJoystickLibrary, its serial port still receives and sends messages.But it's wired

**Comment by lemmingDev** [comment]
So, you just need to receive Serial BT information on the ESP32 and then spit the same info out over USB serial?

**Comment by FANHXIN** [comment]
Esp32 only needs to receive the USB serial port information, and then through the TX pin to the screen RX work is completed

**Comment by lemmingDev** [comment]
Sorry. 

It need to receive information on the USB Serial port?

**Comment by FANHXIN** [comment]
yes

**Comment by lemmingDev** [comment]
And then it transmits that same information over BT Serial?

**Comment by FANHXIN** [comment]
yes

**Comment by FANHXIN** [comment]
Can your library display Bluetooth serial port in PC instead

**Comment by FANHXIN** [comment]
If I can display Bluetooth serial port and controller in PC, I can try it

**Comment by lemmingDev** [comment]
It doesn't really have anything to do with with my library, but yes, I believe you can listen to USB serial information and then transmit that information over BT Serial, at the same time as running the gamepad library over BLE.

You'd just need to be careful with the use of delays

I can probably test it out over the weekend f you don't have anything working by then

**Comment by FANHXIN** [comment]
waiting for your testing, there's nothing I can do

**Comment by lemmingDev** [comment]
Hi

I have tested it and it works fine. Bi-directional communication works very well
Both 
BT Serial --> USB Serial
and
USB Serial --> BT Serial
communication works fine, at the same time as the gamepad

The only issue is that you can't use my new version of the library as NimBLE doesn't seem to allow both BLE and BT to work at the same time. I may update my non - NimBLE version to also have configurable HID soon.

No problem, just use this version of my library for now:
https://github.com/lemmingDev/ESP32-BLE-Gamepad/releases/tag/v0.2.0

Please note the delays in the setup()
They are important so the board doesn't go into a boot loop

The code I added the BT serial functionality is one that maps 10 pins as the first 10 buttons of the  
Please test and get back to me
```
/*
 * This code programs a number of pins on an ESP32 as buttons on a BLE gamepad
 * 
 * It uses arrays to cut down on code
 *
 * Before using, adjust the numOfButtons, buttonPins and physicalButtons to suit your senario
 *
 * This example also includes bi-directional BT Serial <--> USB Serial
 */
 
#include <BleGamepad.h> // https://github.com/lemmingDev/ESP32-BLE-Gamepad
#include "BluetoothSerial.h" 

BleGamepad bleGamepad;
BluetoothSerial SerialBT;

#define numOfButtons 10

byte previousButtonStates[numOfButtons];
byte currentButtonStates[numOfButtons];
byte buttonPins[numOfButtons] = { 0, 35, 17, 18, 19, 23, 25, 26, 27, 32 };
byte physicalButtons[numOfButtons] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };

void setup()
{
  for (byte currentPinIndex = 0 ; currentPinIndex < numOfButtons ; currentPinIndex++)
  {
    pinMode(buttonPins[currentPinIndex], INPUT_PULLUP);
    previousButtonStates[currentPinIndex] = HIGH;
    currentButtonStates[currentPinIndex] =  HIGH;
  }

  bleGamepad.begin();
  bleGamepad.setAutoReport(false);
  delay(1000);
  
  Serial.begin(115200);
  delay(1000);
  SerialBT.begin("ESP32"); //Bluetooth device name
  delay(1000);
  Serial.println("The device started, now you can pair it with bluetooth!");
  delay(1000);
}

void loop()
{
  UpdateGamepad();
  UpdateSerial();
  delay(20);
}

void UpdateSerial()
{
  if (Serial.available()) {
    SerialBT.write(Serial.read());
  }
  if (SerialBT.available()) {
    Serial.write(SerialBT.read());
  }
  
}
void UpdateGamepad()
{
  if(bleGamepad.isConnected())
  {
    for (byte currentIndex = 0 ; currentIndex < numOfButtons ; currentIndex++)
    {
      currentButtonStates[currentIndex]  = digitalRead(buttonPins[currentIndex]);

      if (currentButtonStates[currentIndex] != previousButtonStates[currentIndex])
      {
        if(currentButtonStates[currentIndex] == LOW)
        {
          bleGamepad.press(currentIndex + 1);
        }
        else
        {
          bleGamepad.release(currentIndex + 1);
        }
      } 
    }
    
    if (currentButtonStates != previousButtonStates)
    {
      for (byte currentIndex = 0 ; currentIndex < numOfButtons ; currentIndex++)
      {
        previousButtonStates[currentIndex] = currentButtonStates[currentIndex]; 
      }
      
      bleGamepad.sendReport();
    }
  }
}
```

**Comment by FANHXIN** [comment]
I just can't run tests at the same time. Now I finally know that the new library doesn't support it. Great. I look forward to your updating the new library. I will continue to test for you

**Comment by FANHXIN** [comment]
We'll keep in touch. You can send me an email fanxin39@163.com

**Comment by lemmingDev** [comment]
I updated the post above to add some testing info

**Comment by FANHXIN** [comment]
I have tested that after Bluetooth adaptation, there is no game controller, but the serial port has been displayed

**Comment by FANHXIN** [comment]
#include "BluetoothSerial.h"
#include <BleGamepad.h>
#include <Keypad.h>  

#define PUSH_SHORT 50
#include "driver/pcnt.h"
#define PULSE_INPUT_PIN_A 4  
#define PULSE_CTRL_PIN_A 5 
#define PCNT_H_LIM_VAL 100 
#define PCNT_L_LIM_VAL -100 
#define PULSE_INPUT_PIN_B 12 
#define PULSE_CTRL_PIN_B 13  
#define ROWS 4
#define COLS 4

BluetoothSerial SerialBT;
BleGamepad bleGamepad;

int16_t pcount_A = 0; 
int16_t pcount_B = 0; 
           
int previousButton17State = HIGH;
uint8_t rowPins[ROWS] = {18, 19, 21}; 
uint8_t colPins[COLS] = {22, 23, 25, 26};
uint8_t keymap[ROWS][COLS] = {
  {0,1,2,3},
  {4,5,6,7},
  {8,9,10,11},       
};

Keypad customKeypad = Keypad( makeKeymap(keymap), rowPins, colPins, ROWS, COLS);

void KeypadUpdate(){
      customKeypad.getKeys();
  for (int i=0; i<LIST_MAX; i++){
  if  (customKeypad.key[i].stateChanged){
uint8_t keystate = customKeypad.key[i].kstate;
  if (bleGamepad.isConnected()){
  if (keystate==PRESSED){
      bleGamepad.press(pow(2,(int(customKeypad.key[i].kchar)))); 
}  
  if (keystate==RELEASED){ 
      bleGamepad.release(pow(2,(int(customKeypad.key[i].kchar)))); 
}
      bleGamepad.sendReport();
}
}
}
}
  
void KeyButton(){
  if  (bleGamepad.isConnected()){
       int currentButton17State = digitalRead(27);
  if  (currentButton17State != previousButton17State){
  if  (currentButton17State == LOW){
       bleGamepad.press(BUTTON_17);
      }else{
       bleGamepad.release(BUTTON_17);
}
}
       previousButton17State = currentButton17State;
}
}

void UpdateSerial()
{
  if (Serial.available()) {
    SerialBT.write(Serial.read());
  }
  if (SerialBT.available()) {
    Serial.write(SerialBT.read());
  } 
}

void setup(){
    Serial.begin(115200);
    SerialBT.begin("Wireless Wheel DashHub");
    pinMode(27, INPUT_PULLUP);
    bleGamepad.begin();          
    pcnt_config_t pcnt_config_A; 
    pcnt_config_A.pulse_gpio_num = PULSE_INPUT_PIN_A;
    pcnt_config_A.ctrl_gpio_num = PULSE_CTRL_PIN_A;
    pcnt_config_A.lctrl_mode = PCNT_MODE_REVERSE;
    pcnt_config_A.hctrl_mode = PCNT_MODE_KEEP;
    pcnt_config_A.channel = PCNT_CHANNEL_0;
    pcnt_config_A.unit = PCNT_UNIT_0;
    pcnt_config_A.pos_mode = PCNT_COUNT_INC;
    pcnt_config_A.neg_mode = PCNT_COUNT_DEC;
    pcnt_config_A.counter_h_lim = PCNT_H_LIM_VAL;
    pcnt_config_A.counter_l_lim = PCNT_L_LIM_VAL;
    pcnt_config_t pcnt_config_B;  
    pcnt_config_B.pulse_gpio_num = PULSE_INPUT_PIN_B;
    pcnt_config_B.ctrl_gpio_num = PULSE_CTRL_PIN_B;
    pcnt_config_B.lctrl_mode = PCNT_MODE_REVERSE;
    pcnt_config_B.hctrl_mode = PCNT_MODE_KEEP;
    pcnt_config_B.channel = PCNT_CHANNEL_1;
    pcnt_config_B.unit = PCNT_UNIT_1;
    pcnt_config_B.pos_mode = PCNT_COUNT_INC;
    pcnt_config_B.neg_mode = PCNT_COUNT_DEC;
    pcnt_config_B.counter_h_lim = PCNT_H_LIM_VAL;
    pcnt_config_B.counter_l_lim = PCNT_L_LIM_VAL;             
    pcnt_unit_config(&pcnt_config_A); 
    pcnt_unit_config(&pcnt_config_B);
    pcnt_counter_pause(PCNT_UNIT_0);
    pcnt_counter_clear(PCNT_UNIT_0);
    pcnt_counter_pause(PCNT_UNIT_1);
    pcnt_counter_clear(PCNT_UNIT_1);
    pcnt_counter_resume(PCNT_UNIT_0);
    pcnt_counter_resume(PCNT_UNIT_1);
}

void loop(){
          KeypadUpdate();
          KeyButton();
          UpdateSerial();
    if (bleGamepad.isConnected()){
        pcnt_get_counter_value(PCNT_UNIT_0, &pcount_A);
    if (pcount_A < 0){
          bleGamepad.press(BUTTON_13);
          delay(10);
          bleGamepad.release(BUTTON_13);
          pcnt_counter_clear(PCNT_UNIT_0);
}
    if (pcount_A > 0){
          bleGamepad.press(BUTTON_14);
          delay(10);
          bleGamepad.release(BUTTON_14);
          pcnt_counter_clear(PCNT_UNIT_0);
}
        pcnt_get_counter_value(PCNT_UNIT_1, &pcount_B);
    if (pcount_B < 0){
          bleGamepad.press(BUTTON_15);
          delay(10);
          bleGamepad.release(BUTTON_15);
          pcnt_counter_clear(PCNT_UNIT_1);
}
        if(pcount_B > 0){
          bleGamepad.press(BUTTON_16);
          delay(10);
          bleGamepad.release(BUTTON_16);
          pcnt_counter_clear(PCNT_UNIT_1);
} 
}
}

**Comment by FANHXIN** [comment]
2.0 library, can only use one, controller or serial port, can not run at the same time



I don't know how you realize it. Maybe you are connected to a mobile phone, not a computer. Can you connect to a computer and test it

**Comment by FANHXIN** [comment]
Blegamepad blegamepad; this way, according to your example above, you can only display the serial port, not the controller

Blegamepad blegamepad ("esp32", "esp32"); after setting the name, the computer recognizes the controller and the serial port cannot be used

**Comment by lemmingDev** [comment]
Seems to work fine for me 

In any case, I've just ported all of the new functionality over to the non - NimBLE version of my library

I will upload it to Github soon and mark it as Release 3.1

**Comment by FANHXIN** [comment]
When do you upload it? I'll download it

**Comment by lemmingDev** [comment]
https://github.com/lemmingDev/ESP32-BLE-Gamepad/releases/tag/v0.3.1

It's there now

**Comment by lemmingDev** [comment]
I tried to make it very clear in my post where I gave my code

**Please note the delays in the setup()**

Try it with the delays as in my code

**Comment by FANHXIN** [comment]
Your code 0.2.0 has no effect in my test. I'm already trying 0.3.1

**Comment by FANHXIN** [comment]
0.3.1， Still，you code

**Comment by FANHXIN** [comment]
Can you find your controller in the controller of windows in PC

**Comment by lemmingDev** [comment]
First time, I could only see one device to pair, but when I paired it, it paired both.

I found both devices in the Windows BT devices list.

When I unpair both of them, and searched again, I found both of them in the search

Try pairing it once, and then unpairing it, then search again. As you can see, I can see both of them

![image](https://user-images.githubusercontent.com/15526971/114171921-52404100-9978-11eb-9afe-53a3096b4d76.png)

Please use this code with delays
```
#include "BluetoothSerial.h"
#include <BleGamepad.h>
#include <Keypad.h>

#define PUSH_SHORT 50
#include "driver/pcnt.h"
#define PULSE_INPUT_PIN_A 4
#define PULSE_CTRL_PIN_A 5
#define PCNT_H_LIM_VAL 100
#define PCNT_L_LIM_VAL -100
#define PULSE_INPUT_PIN_B 12
#define PULSE_CTRL_PIN_B 13
#define ROWS 4
#define COLS 4

BluetoothSerial SerialBT;
BleGamepad bleGamepad;

int16_t pcount_A = 0;
int16_t pcount_B = 0;

int previousButton17State = HIGH;
uint8_t rowPins[ROWS] = { 18, 19, 21 };
uint8_t colPins[COLS] = { 22, 23, 25, 26 };
uint8_t keymap[ROWS][COLS] = {
{0,1,2,3},
{4,5,6,7},
{8,9,10,11},
};

Keypad customKeypad = Keypad(makeKeymap(keymap), rowPins, colPins, ROWS, COLS);

void KeypadUpdate() {
	customKeypad.getKeys();
	for (int i = 0; i < LIST_MAX; i++) {
		if (customKeypad.key[i].stateChanged) {
			uint8_t keystate = customKeypad.key[i].kstate;
			if (bleGamepad.isConnected()) {
				if (keystate == PRESSED) {
					bleGamepad.press(pow(2, (int(customKeypad.key[i].kchar))));
				}
				if (keystate == RELEASED) {
					bleGamepad.release(pow(2, (int(customKeypad.key[i].kchar))));
				}
				bleGamepad.sendReport();
			}
		}
	}
}

void KeyButton() {
	if (bleGamepad.isConnected()) {
		int currentButton17State = digitalRead(27);
		if (currentButton17State != previousButton17State) {
			if (currentButton17State == LOW) {
				bleGamepad.press(BUTTON_17);
			}
			else {
				bleGamepad.release(BUTTON_17);
			}
		}
		previousButton17State = currentButton17State;
	}
}

void UpdateSerial()
{
	if (Serial.available()) {
		SerialBT.write(Serial.read());
	}
	if (SerialBT.available()) {
		Serial.write(SerialBT.read());
	}
}

void setup() {

	bleGamepad.begin();
	delay(1000);
	Serial.begin(115200);
	delay(1000);
	SerialBT.begin("Wireless Wheel DashHub");
	delay(1000);
	pinMode(27, INPUT_PULLUP);

	delay(1000);
	pcnt_config_t pcnt_config_A;
	pcnt_config_A.pulse_gpio_num = PULSE_INPUT_PIN_A;
	pcnt_config_A.ctrl_gpio_num = PULSE_CTRL_PIN_A;
	pcnt_config_A.lctrl_mode = PCNT_MODE_REVERSE;
	pcnt_config_A.hctrl_mode = PCNT_MODE_KEEP;
	pcnt_config_A.channel = PCNT_CHANNEL_0;
	pcnt_config_A.unit = PCNT_UNIT_0;
	pcnt_config_A.pos_mode = PCNT_COUNT_INC;
	pcnt_config_A.neg_mode = PCNT_COUNT_DEC;
	pcnt_config_A.counter_h_lim = PCNT_H_LIM_VAL;
	pcnt_config_A.counter_l_lim = PCNT_L_LIM_VAL;
	pcnt_config_t pcnt_config_B;
	pcnt_config_B.pulse_gpio_num = PULSE_INPUT_PIN_B;
	pcnt_config_B.ctrl_gpio_num = PULSE_CTRL_PIN_B;
	pcnt_config_B.lctrl_mode = PCNT_MODE_REVERSE;
	pcnt_config_B.hctrl_mode = PCNT_MODE_KEEP;
	pcnt_config_B.channel = PCNT_CHANNEL_1;
	pcnt_config_B.unit = PCNT_UNIT_1;
	pcnt_config_B.pos_mode = PCNT_COUNT_INC;
	pcnt_config_B.neg_mode = PCNT_COUNT_DEC;
	pcnt_config_B.counter_h_lim = PCNT_H_LIM_VAL;
	pcnt_config_B.counter_l_lim = PCNT_L_LIM_VAL;
	pcnt_unit_config(&pcnt_config_A);
	pcnt_unit_config(&pcnt_config_B);
	pcnt_counter_pause(PCNT_UNIT_0);
	pcnt_counter_clear(PCNT_UNIT_0);
	pcnt_counter_pause(PCNT_UNIT_1);
	pcnt_counter_clear(PCNT_UNIT_1);
	pcnt_counter_resume(PCNT_UNIT_0);
	pcnt_counter_resume(PCNT_UNIT_1);
}

void loop() {
	KeypadUpdate();
	KeyButton();
	UpdateSerial();
	if (bleGamepad.isConnected()) {
		pcnt_get_counter_value(PCNT_UNIT_0, &pcount_A);
		if (pcount_A < 0) {
			bleGamepad.press(BUTTON_13);
			delay(10);
			bleGamepad.release(BUTTON_13);
			pcnt_counter_clear(PCNT_UNIT_0);
		}
		if (pcount_A > 0) {
			bleGamepad.press(BUTTON_14);
			delay(10);
			bleGamepad.release(BUTTON_14);
			pcnt_counter_clear(PCNT_UNIT_0);
		}
		pcnt_get_counter_value(PCNT_UNIT_1, &pcount_B);
		if (pcount_B < 0) {
			bleGamepad.press(BUTTON_15);
			delay(10);
			bleGamepad.release(BUTTON_15);
			pcnt_counter_clear(PCNT_UNIT_1);
		}
		if (pcount_B > 0) {
			bleGamepad.press(BUTTON_16);
			delay(10);
			bleGamepad.release(BUTTON_16);
			pcnt_counter_clear(PCNT_UNIT_1);
		}
	}
}
```

**Comment by lemmingDev** [comment]
BTW - They will both take on the name "Wireless Wheel DashHub" when paired

![image](https://user-images.githubusercontent.com/15526971/114172619-39845b00-9979-11eb-9872-2bf1ab1bf2be.png)
![image](https://user-images.githubusercontent.com/15526971/114172660-4903a400-9979-11eb-82e6-ccc798d1ee14.png)

**Comment by lemmingDev** [comment]
Oh, and you should see 2 new serial ports in Windows

One of them is the BT Serial port

**Comment by lemmingDev** [comment]
Anyway - I'm done with coding for tonight

Good luck

**Comment by FANHXIN** [comment]
Why can't I

**Comment by FANHXIN** [comment]
Same library, same code, my God

**Comment by FANHXIN** [comment]
succeed

**Comment by FANHXIN** [comment]
I finally know why

Delay is important

**Comment by FANHXIN** [comment]
Now two devices can be found, but after connecting one device and the other device, the controller still cannot be found

**Comment by FANHXIN** [comment]
I'm happy too soon

**Comment by FANHXIN** [comment]
At least two devices can be found now, and I will continue

**Comment by FANHXIN** [comment]
If Bluetooth is adapted to the controller and then to the Bluetooth serial port, the controller will delete the adapter from the adapter and replace it with the Bluetooth serial port, which can not be used at the same time

**Comment by lemmingDev** [comment]
I'm not sure

While connected to the gamepad on your PC with BLE, have you tried looking for the BT serial on your phone?

**Comment by FANHXIN** [comment]
Hi, buddy!

I thought all night and came up with an idea.

Can you call the serial port code from BT library and directly add it to your new library, so that the new library can display the serial port directly in PC

**Comment by FANHXIN** [comment]
In this way, there is no need to write code to adapt two devices

**Comment by FANHXIN** [comment]
What do you think of the idea？

**Comment by FANHXIN** [comment]
I think a single development board can make the adapter match two devices at the same time, and the two communication addresses must be complex. In my opinion, if a development board still uses a communication address to realize two functions, it is obviously much simpler

**Comment by lemmingDev** [comment]
> I think a single development board can make the adapter match two devices at the same time, and the two communication addresses must be complex. In my opinion, if a development board still uses a communication address to realize two functions, it is obviously much simpler

This is out of scope for this library

Feel free to make a fork and give it a go if you like

I'll close this thread now as I've released the configurable HID library (non NimBLE):
https://github.com/lemmingDev/ESP32-BLE-Gamepad/releases/tag/v0.3.1

Feel free to open another issue
