### ISSUE TITLE
The operation in the code needs ble and Bluetooth serial port

### ISSUE THREAD

**Issue by FANHXIN** [lemmingDev/ESP32-BLE-Gamepad#58]
https://desire.giesecke.tk/index.php/2018/02/27/esp32-bluetooth-serial-and-ble-server-running-together/

https://github.com/beegee-tokyo/ESP32-Weatherstation/blob/master/src/ble_bt.cpp

**Comment by FANHXIN** [comment]
I'm also trying to modify 
hope to help you

**Comment by pipech90** [comment]
Hi!

I have a problem.  I am trying to make a gamepad for pc.  But the PC does not see it in a bluetooth environment.  My phone sees and connects.  I tried to find it using Windows 8.1 and 10. What could be the problem?

**Comment by lemmingDev** [comment]
> Hi!
> 
> I have a problem. I am trying to make a gamepad for pc. But the PC does not see it in a bluetooth environment. My phone sees and connects. I tried to find it using Windows 8.1 and 10. What could be the problem?

You need at least Bluetooth 4.0...

**Comment by lemmingDev** [comment]
This library currently uses the NimBLE Bluetooth library for communication
Unfortunately, that library is not compatible with using classic Bluetooth UART (creates a standard COM port) at the same time
I may create another version that uses the default version of ESP32 BLE Arduino at a later stage.

Apparently, NimBLE can be used to create BLE UART (standard COM port not created), and there is an example in the NimBLE directory, however this library would need modification for it to work. May have a look at it at a later stage, however if someone wants to submit a pull request, then be my guest
