### ISSUE TITLE
Feature request: Add support for haptic feedback

### ISSUE THREAD

**Issue by JB515** [lemmingDev/ESP32-BLE-Gamepad#62]
I've only recently started using this library for several projects but I really love how easy it is to get up and running and how reliable my controller is so far. One thing that would be really great to have is haptic feedback for vibrating (rumble) motors and/or force feedback joysticks/steering wheels.

Is this technically possible within the constraints of what is presumably a standard for BLE gamepads? Is there such a thing as BLE PID devices? I'll probably end up looking into this myself properly sooner or later but it would be great if someone more knowledgeable than me (so basically, anyone!) knows how difficult this would be.

**Comment by lemmingDev** [comment]
Hi

Glad you're using the library and are able to get it working.

Rumble/feedback has been discussed before (look at the closed issues), but I'm just not sure how to do it.
Most of the BT code was written by others (this project is a modification of a BLE mouse library), and I'm not too knowledgeable in that arena. 

If someone makes a pull request with it working, I'll be sure to add it...
