### ISSUE TITLE
Can't add service to receive data

### ISSUE THREAD

**Issue by Thelitteone** [lemmingDev/ESP32-BLE-Gamepad#67]
Hello, is there a possibility to add a service that allows me to receive data via bluetooth UART on the gamecontroller.
I would like to use this received data to trigger an action like pressing button 5.
Thank you very much

**Comment by lemmingDev** [comment]
This library currently uses the NimBLE Bluetooth library for communication
Unfortunately, that library is not compatible with using classic Bluetooth UART (creates a standard COM port) at the same time
I may create another version that uses the default version of ESP32 BLE Arduino at a later stage.

Apparently, NimBLE can be used to create BLE UART (standard COM port not created), and there is an example in the NimBLE directory, however this library would need modification for it to work. May have a look at it at a later stage, however if someone wants to submit a pull request, then be my guest
