### ISSUE TITLE
USB gamepad help

### ISSUE THREAD

**Issue by ccc9090** [lemmingDev/ESP32-BLE-Gamepad#68]
Hello,

I am new to circuits and arduino so I am sorry if these are dump/simple questions.

I am trying to use an esp32 adafruit feather to turn a [wired usb gamepad](https://www.amazon.com/gp/product/B08HCPDGT3/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1) into a wireless one for pc. I am having a hard time getting from the usb to your code. I plan to remove the cable and solder jumpers inplace to  pins on the board (still not sure which ones or if that would work). Any thoughts or help?

**Comment by lemmingDev** [comment]
Look over the examples and try to understand I guess...
