### ISSUE TITLE
Is it compatible with ESP8266?

### ISSUE THREAD

**Issue by RarePotato8DE** [lemmingDev/ESP32-BLE-Gamepad#71]
Dear lemmingDev,

I'm glad I found out about your awesome project and now I am really interested in doing a bluetooth HID device by myself.
The problem is, that I'm not really experienced so I was wondering if this project also works on a ESP8266 microcontroller like a Wemos D1 Mini or if it only works on ESP32.

Thanks in advance for your help and keep up the great work!
Kind regards

**Comment by lemmingDev** [comment]
Hi

ESP8266 does not have Bluetooth...

**Comment by RarePotato8DE** [comment]
Ohh.. right. I'm sorry.
I had in mind that it has Bluetooth, but it was WiFi I was thinking of.
Thanks for your help, I'll get a compatible ESP32.
You have a good day.
