### ISSUE TITLE
HAT switch + multiple buttons example

### ISSUE THREAD

**Issue by gigawatts** [lemmingDev/ESP32-BLE-Gamepad#78]
Would you happen to have a good example, similar to `MultipleButtons.ino` but also including a HAT switch? the if ... else if ... else { assume centered } code I attempted was not happy, as I believe it is trying to rapidly send the "I'm still centered" report very rapidly which results in the PC disconnecting and reconnecting the BLE connection constantly.

I'm sure I could get something to work eventually, but just curious if you have an un-published solution already.

Thanks and awesome library!

**Comment by devops724** [comment]
Hi , when i send DPAD_UP  bleGamepad.press(DPAD_UP)
it press on A button in windows and android game controllers
