### ISSUE TITLE
> i have 4.0, 4.2 and 5.0.

### ISSUE THREAD

**Issue by pipech90** [lemmingDev/ESP32-BLE-Gamepad#86]

**Comment by lemmingDev** [comment]
Hi

Not sure why it wouldn't work. Have had it working on dozens of Windows PCs without issue
Have you got any other Windows PCs to try it with.
Could be a software / driver issue

**Comment by pipech90** [comment]
lemmingDev, thanks, found another computer.  He sees the device.  But a second after connecting, it disconnects.
